### PR TITLE
Pull request for XGBoost docs - v. 0.90

### PR DESCRIPTION
**Pull request by capac**
XGBoost docs created from HTML files from the stable version 0.90

### CODE REVIEW

**Comment by Kapeli** [comment]
Are the changes to `altair.tgz` and `statsmodels.tgz` intentional?

**Comment by capac** [comment]
They are not intentional for either, sorry.

**Comment by Kapeli** [comment]
In that case please remove the changes from your pull request.

**Comment by capac** [comment]
I think this should work. I reverted back to the commit where `altair.tgz` and `statsmodels.tgz` were unchanged, fetched upstream and merged to my fork and then submitted my modified fork to GitHub. Please let me know if this can work.

**Comment by Kapeli** [comment]
Can you open a new pull request please? I'm still seeing changes to `altair.tgz` and `statsmodels.tgz`.

**Pull request closed without merging**
