### PR TITLE
Update WPILib to 2023.4.3

### PR DESCRIPTION
**Pull request by admlvntv**

### CODE REVIEW

**Comment by admlvntv** [comment]
What I did I do wrong?

**Comment by admlvntv** [comment]
@jhh as you were the last one to do this, do you know what I could be doing wrong? also, how did you add a table of contents?

**Comment by jhh** [comment]
I haven't looked at this for a while but if it helps, here's the build script I used:

```sh
#!/bin/bash

rm -rf WPILib.docset WPILib.tgz
javadocset WPILib /tmp/allwpilib-2022.1.1/docs/build/docs/javadoc
cp Info.plist WPILib.docset/Contents/
cp *.png WPILib.docset
tar --exclude='.DS_Store' -cvzf WPILib.tgz WPILib.docset
```

`Info.plist`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>CFBundleIdentifier</key>
        <string>wpilib</string>
        <key>CFBundleName</key>
        <string>WPILib</string>
        <key>DocSetPlatformFamily</key>
        <string>wpilib</string>
        <key>dashIndexFilePath</key>
        <string>overview-summary.html</string>
        <key>DashDocSetFamily</key>
        <string>java</string>
        <key>isDashDocset</key>
        <true/>
        <key>DashDocSetFallbackURL</key>
        <string>https://first.wpi.edu/wpilib/allwpilib/docs/release/java/</string>

    </dict>
</plist>
```

Not sure on the GitHub action error, I don't believe they were run when I last updated.

**Comment by admlvntv** [comment]
This is helpful, thanks. I realize that when running the javadocset command, it is actually not returning anything for the docset, just repeating "Warning: could not determine type for . Please tell the developer about this!" over and over. There might be some formatting issues in the javadoc when it is created, but I'm not sure what.

**Comment by admlvntv** [comment]
The database is simply empty, and all it did was copy the javadoc files into the Documents folder
CleanShot 2023-10-22 at 09 36 23@2x

**Comment by admlvntv** [comment]
Ready to merge (:

**Comment by Kapeli** [comment]
Please redo your fork so that AWS_CLI and the others are not included in your pull request.

**Pull request closed without merging**
