### PR TITLE
jax 0.3.21

### PR DESCRIPTION
**Pull request by graelo**
This docset is an updated version, produced as described in the jax/README.md

I did not remove the jax.tgz.txt

### CODE REVIEW

**Comment by Kapeli** [comment]
Please don't include the unarchived docset.

**Comment by ppwwyyxx** [comment]
FYI, I think my version at https://github.com/ppwwyyxx/dash-docset-jax produces nicer docs. It contains a few html&css fixes to make the doc look cleaner and nicer inside dash.

**Comment by ppwwyyxx** [comment]
Sent PR #3919

**Comment by graelo** [comment]
Thanks! I'll close mine.

**Pull request closed without merging**
