### PR TITLE
PHPUnit 9.5

### PR DESCRIPTION
**Pull request by Max13**

### CODE REVIEW

**Comment by Kapeli** [comment]
Great work. Is it ok if I use this to update the main PHPUnit docset instead of adding it to user contributed?

**Comment by Max13** [comment]
Do it man! I will be glad to participate to a main docset 😁

I'm currently working on adding the API documentation.

**Comment by Max13** [comment]
BTW, if you use my contribution for the main docset, do I still commit to this if I update the script?

**Comment by Kapeli** [comment]
Yes please. I'm not sure on how I'll integrate the script yet, but please do update the pull request.

**Comment by Max13** [comment]
I'm trying to achieve the same presentation as Laravel for instance, with the class' names on the left and the namespace smaller in gray:
Capture d’écran 2022-08-27 à 02 42 28
 
This is, instead, what I get:
Capture d’écran 2022-08-27 à 02 42 21
 
Can you explain me what is responsible for showing the gray part and how to show (in the lists) only the class name/arguments/methods without the fill namespace please?

**Comment by Kapeli** [comment]
> Can you explain me what is responsible for showing the gray part and how to show (in the lists) only the class name/arguments/methods without the fill namespace please?

Sorry. I missed this question.

Try to add this to your `Info.plist` and remove and re-add the docset:
```xml
<key>DashDocSetNameShorteningFamily</key>
<string>phpShortening</string>
```

If this doesn't give you the result you're after, let me know and I'll provide an alternative.

**Comment by Kapeli** [comment]
I've released the 9.5 docset 🥳 

Sorry for the wait!

**Pull request merged**
