### PR TITLE
Splunk enterprise docs

### PR DESCRIPTION
**Pull request by mariajyu**
Add Splunk enterprise docs to dash.

### CODE REVIEW

**Comment by mariajyu** [comment]
I see I am missing a retina icon, is this required? Documentation seems to say this is optional. 
I can ask around if necessary but it's difficult for me to track down an 16x16 retina icon for this purpose.

**Comment by Kapeli** [comment]
Retina icons are required for user contributions. They are not required for when you're adding an icon inside the docset itself. Sorry for the confusion!

Do this: take the current icon and resize it to 32x32 for retina (named `icon@2x.png`) and to 16x16 for regular size (named `icon.png`).

**Comment by mariajyu** [comment]
Thanks for the guidance!

**Comment by Kapeli** [comment]
Awesome. Thank you! :+1:

**Pull request merged**
