### PR TITLE
Update React Native v0.4.3

### PR DESCRIPTION
**Pull request by epitaphmike**

### CODE REVIEW

**Comment by Kapeli** [comment]
Please redo your fork and resubmit (squash your commits into one).

**Comment by epitaphmike** [comment]
What is the best way you'd propose to do this? My current master branch is the same as your just with my new changes. Other than the squash, the commit was ok yes?

**Comment by Kapeli** [comment]
Yep, looks fine. I'm not that good with git, so there might be an easier way than this, but one way is to just delete your fork and redo it and then apply the changes for 0.4.3 and resubmit your pull request.

**Comment by epitaphmike** [comment]
So what's the reason for the squash?

**Comment by Kapeli** [comment]
It's easier to review your changes in one commit. I also remove all `tgz` files from this repo to keep it small. Your pull requests re-adds the `tgz`s back.

**Pull request closed without merging**
