### PR TITLE
Basscss initial

### PR DESCRIPTION
**Pull request by VictorHom**
I removed the https links. Will this pass travis?

### CODE REVIEW

**Comment by Kapeli** [comment]
You have some links that start with `//`. Any idea what's up with them and what they should point to? Only relative file paths are supported.

**Comment by VictorHom** [comment]
I think Im going to remove them. They look like they are links from the the author, but don't add to the actual documentation

**Comment by VictorHom** [comment]
@Kapeli just a heads up - I removed the links with /

**Comment by Kapeli** [comment]
Looks good. Please remove the `versions` folder since the sample stuff in it is useless.

**Comment by VictorHom** [comment]
@Kapeli removed the versions folder

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request closed without merging**
