### PR TITLE
update plotnine to 0.13.4

### PR DESCRIPTION
**Pull request by ivaquero**

### CODE REVIEW

**Comment by ivaquero** [comment]
> Test result: **FAIL** 🔴
> 
> ```
> plotnine/versions/0.13.4/plotnine.tgz: FAIL ❌
> Could not load entries at "plotnine.docset"
> [WARNING] Detected online resource for: dashIndexFilePath
> [REQUEST] https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,300;0,400;0,700;1,400&display=swap
> [REQUEST] https://fonts.gstatic.com/s/sourcesanspro/v22/6xK3dSBYKcSV-LCoeQqfX1RYOo3aOqTimDc.woff2
> [REQUEST] https://fonts.gstatic.com/s/sourcesanspro/v22/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPa7lujVj9w.woff2
> [REQUEST] https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg
> ```

Not sure what caused this, font?

**Comment by Kapeli** [comment]
The `docSet.dsidx` of the docset is empty.

```bash
» sqlite3 docSet.dsidx "SELECT COUNT(id) FROM searchIndex" 
0
```

**Comment by ivaquero** [comment]
I added the archive, but the error is still there.

**Comment by Kapeli** [comment]
> The `docSet.dsidx` of the docset is empty.
> 
> ```shell
> » sqlite3 docSet.dsidx "SELECT COUNT(id) FROM searchIndex" 
> 0
> ```

The error is caused by this ☝️

**Comment by ivaquero** [comment]
Unluckily, I don't know how to solve this.

**Comment by Kapeli** [comment]
The docset is not indexed. If the docset works locally for you, then it means it's some kind of archiving issue and/or you're archiving the wrong docset.

**Pull request closed without merging**
