### PR TITLE
Initial commit of Google Closure Docset.

### PR DESCRIPTION
**Pull request by wesalvaro**

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:

```
Found regular icon, but missing retina icon in "goog"
Checking goog/goog.tgz...
File not found at "api/http://en.wikipedia.org/wiki/Advanced_Encryption_Standard" for entry with row id "29513" of "goog.docset"
File not found at "api/http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation" for entry with row id "29514" of "goog.docset"
Found entry with new line in its name at row id "29602" at "goog.docset". Complete entry name is: "http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation
#Cipher-block_chaining_.28CBC.29"
File not found at "api/http://en.wikipedia.org/wiki/Block_cipher_modes_of_operation
" for entry with row id "29602" of "goog.docset"
File not found at "api/http://www.w3.org/TR/REC-CSS2/selector.html" for entry with row id "29735" of "goog.docset"
File not found at "api/http://www.google.com/data/search?q=monkey&callback=mycb" for entry with row id "29822" of "goog.docset"
File not found at "api/http://www.monkey.com" for entry with row id "29823" of "goog.docset"
File not found at "api/http://crbug.com/153122" for entry with row id "30095" of "goog.docset"
File not found at "api/http://go/l2binary" for entry with row id "30365" of "goog.docset"
File not found at "api/http://wiki/Main/ClosureKeyboardAccessible" for entry with row id "30446" of "goog.docset"
File not found at "api/class_TestPlugin.html" for entry with row id "31368" of "goog.docset"
File not found at "api/class_TestEvent.html" for entry with row id "32419" of "goog.docset"
File not found at "api/class_Animation.html" for entry with row id "33102" of "goog.docset"
File not found at "api/http://url" for entry with row id "33240" of "goog.docset"
File not found at "api/http://wiki/Main/TemplatesAndBiDi" for entry with row id "33355" of "goog.docset"
File not found at "api/http://go/js_locale_data" for entry with row id "55085" of "goog.docset"
File not found at "api/http://icu-project.org/apiref/icu4j/com/ibm/icu/util/GenderInfo.html" for entry with row id "55484" of "goog.docset"
File not found at "api/http://icu-project.org/apiref/icu4j/com/ibm/icu/text/ListFormatter.html" for entry with row id "55486" of "goog.docset"
File not found at "api/class_MockWebChannelBase.html" for entry with row id "58861" of "goog.docset"
File not found at "api/class_MockDate.html" for entry with row id "59514" of "goog.docset"
File not found at "api/class_TestHandler_.html" for entry with row id "59536" of "goog.docset"
File not found at "api/class_MockChannelRequest.html" for entry with row id "60381" of "goog.docset"
File not found at "api/class_MockBrowserChannel.html" for entry with row id "60508" of "goog.docset"
File not found at "api/http://path/to/image.gif" for entry with row id "60666" of "goog.docset"
File not found at "api/http://google.com" for entry with row id "60748" of "goog.docset"
File not found at "api/class_CrossPageChannel.html" for entry with row id "60929" of "goog.docset"
File not found at "api/http://promisesaplus.com" for entry with row id "61340" of "goog.docset"
File not found at "api/class_proto2_TestAllTypes_NestedMessage.html" for entry with row id "61418" of "goog.docset"
File not found at "api/class_proto2_TestAllTypes_OptionalGroup.html" for entry with row id "61419" of "goog.docset"
File not found at "api/class_proto2_TestAllTypes_RepeatedGroup.html" for entry with row id "61420" of "goog.docset"
File not found at "api/class_proto2_TestDefaultChild.html" for entry with row id "61421" of "goog.docset"
File not found at "api/class_proto2_TestDefaultParent.html" for entry with row id "61422" of "goog.docset"
File not found at "api/class_SanitizedContentSubclass.html" for entry with row id "61618" of "goog.docset"
File not found at "api/class_PerfectlySlowStat.html" for entry with row id "61646" of "goog.docset"
Found entry with new line in its name at row id "61907" at "goog.docset". Complete entry name is: "goog.string.specialEscapeChars_.
"
File not found at "api/class_Set.html" for entry with row id "62246" of "goog.docset"
File not found at "api/http://www.w3.org/TR/webstorage/" for entry with row id "63572" of "goog.docset"
File not found at "api/http://protobuf.googlecode.com/svn/trunk/python/stubout.py" for entry with row id "63637" of "goog.docset"
File not found at "api/http://go/closure_control_subclassing" for entry with row id "64152" of "goog.docset"
File not found at "api/http://search.yahoo.com/mrss/" for entry with row id "64169" of "goog.docset"
File not found at "api/http://goto/datanode" for entry with row id "64170" of "goog.docset"
File not found at "api/class_HasString.html" for entry with row id "64517" of "goog.docset"
File not found at "api/class_svgpan_SvgPan.html" for entry with row id "65437" of "goog.docset"
```

Other issue:

* The index page doesn't work. See https://kapeli.com/docsets#settingindexpage.

**Comment by wesalvaro** [comment]
Yeah, you should really put the instructions for doing the local verification on the README instead of in the Travis output. You didn't even mention it in the comment above... =\

It would have saved me a lot of time.

I think it would also make sense to leave this open so the PR commit could be updated instead of having to create a new PR everytime.

**Comment by Kapeli** [comment]
> Yeah, you should really put the instructions for doing the local verification on the README instead of in the Travis output.

The verification might output some less-than-obvious errors. I prefer it if pull requests are opened and I get to see the error log and give suggestions for less obvious errors, if needed.

> It would have saved me a lot of time.

How?

> I think it would also make sense to leave this open so the PR commit could be updated instead of having to create a new PR every time.

I don't like having open issues which are just waiting for action from the submitter. My job regarding your issue is done, so I closed it. When you're ready, open a new one. The discomfort for you shouldn't be that high since it's just a button press to open a new issue.

**Comment by wesalvaro** [comment]
How?
I would have fixed the issues before pushing my changes, creating a pull request, waiting on Travis only to see I could have saved all that time by just checking it myself.

Your attitude toward user contributions is disconcerting...

**Comment by Kapeli** [comment]
> I would have fixed the issues before pushing my changes, creating a pull request, and waiting on Travis only to see I could have saved all that time by just checking it myself.

I see. I didn't realise contributors wait for Travis. Even so, I think it's better if contributors wait for Travis instead of running things themselves because there are a lot of things that can go wrong during validation (e.g. false positives).

By the way, you can see what Travis does by checking the [`.travis.yml`](https://github.com/Kapeli/Dash-User-Contributions/blob/master/.travis.yml). I think this applies for all repos that use Travis.

> Your attitude toward user contributions is disconcerting...

I don't really see how. You raised some issues about how contributions work and how I handle issues, and I told you why things are the way they are.

**Comment by wesalvaro** [comment]
True... I guess I'll just have to scrounge through travis.yml files when I contribute to things.

Because I'm helping make your product better. It does me no good at all. I have the docset.

You could be a little more helpful, nicer, and more considerate of mine and other contributors time.

**Comment by Kapeli** [comment]
> True... I guess I'll just have to scrounge through travis.yml files when I contribute to things.

No one told you to. To the contrary, I discouraged it in the case of this repo.

> You could be a little more helpful

I have set up the contributions in such a way that I can give relevant feedback and personally tell contributors what they need to do. I also respond very fast to new contributions and try not to leave pull requests waiting for a long time. If you have any suggestions on how I could be more helpful, let me know.

> nicer

I think I'm nice. Here's me not being nice: you failed to follow the simple 10 or so [contribution steps](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset) and because of that you failed to add the icon properly. And then you complain about me wasting your time by not letting you verify locally and fail even more? Well here's me complaining about you wasting my time. Now back to being nice...

> and more considerate of my (and other contributors') time.

I am considerate of your time. That's why I tried to explain why you should not validate locally because it would just lead to more issues. I hope you understood the reasons...

> Because I'm helping make your product better. It does me no good at all. I have the docset.

I highly appreciate all contributions. That doesn't mean that I'm required to add instructions in the README that would confuse other contributors, just because you want me to.

**Comment by wesalvaro** [comment]
How would that confuse other contributors? Testing locally with the validator saved me so much time. If I had to create a pull request and wait for you to comment on why it failed for every time I wanted to test my docset, I would have never submitted it. It would have been a supreme waste of time.

The fact that you're arguing with me over this is crazy.

**Comment by Kapeli** [comment]
> The fact that you're arguing with me over this is crazy.

Yeah, I guess you know what the validation tool does specifically and understand it completely... I'm sorry for being crazy.

I really don't feel like going into what the validation tool does and where it can go wrong. I've given plenty reasons why it's a bad idea for all contributors to run it themselves.

To reiterate:

> The verification might output some less-than-obvious errors. I prefer it if pull requests are opened and I get to see the error log and give suggestions for less obvious errors, if needed.

> I think it's better if contributors wait for Travis (and my input) instead of running things themselves because there are a lot of things that can go wrong during validation (e.g. false positives).

**Comment by wesalvaro** [comment]
I totally understand and appreciate that you want to help yourself, but I just don't think it's feasible.

I ran the validator locally probably >50 times and I had no issues understanding the output. I just can't imagine having to do >50 PRs. lol

**Pull request closed without merging**
