### PR TITLE
Adds docset for Diesel

### PR DESCRIPTION
**Pull request by zamith**

### CODE REVIEW

**Comment by Kapeli** [comment]
Small issues: the names for the icon files are `icon.png` and `icon@2x.png`, not `logo.png` and `logo@2x.png`.

**Comment by zamith** [comment]
Done.

**Comment by Kapeli** [comment]
Icon issues:

```
Not 16x16: "icon.png" in "diesel"
Not 32x32: "icon@2x.png" in "diesel"
```

**Comment by zamith** [comment]
Yes, I saw that. I think it's fixed now.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request merged**
