### PR TITLE
Add pup docset

### PR DESCRIPTION
**Pull request by Pysis868**
Followed the guide.
 - Generated and configured actual docset files.
 - Reviewed Contribution Checklist, versioning guidelines.
 - Copied, added changes, and committing to own fork of the main repo.

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:

```
Found retina icon (@2x), but missing regular icon in "pup"
Could not find docSet.dsidx at "pup.docset/Contents/Resources/docSet.dsidx"
```

**Comment by Pysis868** [comment]
Only provided larger icon based on wording in the following Docset Generation Guide instructions:

https://kapeli.com/docsets#dashDocset
```
3. Add an Icon

...

The size of the icon should be 16x16 or 32x32. For Retina display support, you can either use a single 32x32 icon or 2 separate icons: icon.png (16x16) and icon@2x.png (32x32).

...
```

Fixed docSet.dsidx location.

**Comment by Kapeli** [comment]
Those instructions are for adding the icon within the docset itself, not within this repo:

```
To set a custom icon for your docset, simply add a icon.png file directly inside the docset bundle. For example, the file path would be <docset name>.docset/icon.png.
```

The instructions for this repo are at https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset:

```
Include a icon.png and icon@2x.png with sizes 16x16 and 32x32 or simply delete the sample icon if you don't want an icon at all
```

**Comment by Kapeli** [comment]
The anchors in the URLs in docSet.dsidx don't work. For example, you link to `README.html#basic-usage`, but `#basic-usage` doesn't exist. `#user-content-basic-usage` exists.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
