### PR TITLE
Added Parse. v1.10.0

### PR DESCRIPTION
**Pull request by Lukapp**

### CODE REVIEW

**Comment by Kapeli** [comment]
You need to update the archive at `docsets/Parse_iOS_SDK/Parse-iOS-SDK.tgz` too.

**Comment by Lukapp** [comment]
Sorry, I just changed the path

**Comment by Kapeli** [comment]
No, don't change the path. The archive needs to be there at both locations.

**Comment by Lukapp** [comment]
Ok. Done

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request merged**
