### PR TITLE
Added docset for PyGame

### PR DESCRIPTION
**Pull request by LOVE-2-CODE**
Hey Kapeli,

I'm LOVE-2-CODE and I have created a PyGame docset. It has the full PyGame documentation including an icon. I used the generation script linked on your website. If you have any issues with it please let me know and I will fix it ASAP.

Thanks, LOVE-2-CODE

### CODE REVIEW

**Comment by LOVE-2-CODE** [comment]
Whoops, just had an error with the naming of my 32X32 icon. Totally my fault, should be fixed now :smile:

**Comment by Kapeli** [comment]
Please redo your fork and submit a new pull request.

**Comment by LOVE-2-CODE** [comment]
What needs to be redone?

**Comment by Kapeli** [comment]
The fork. Delete it and redo it.

**Comment by LOVE-2-CODE** [comment]
Ok

**Pull request closed without merging**
