### PR TITLE
Add Perl6 docset

### PR DESCRIPTION
**Pull request by davepagurek**

### CODE REVIEW

**Comment by davepagurek** [comment]
So CI is failing for URI-encoded paths with unicode filenames while Dash itself reads these without problem. Leaving unicode characters in the paths in the database makes Dash not be able to open the files, even though they exist. Thoughts?

**Comment by Kapeli** [comment]
The test failed because of an error in the verification tool. Sorry about that. I've fixed it now and it shouldn't fail the next time.

Now about the docset... What's the deal with Perl 6? Is it an official release? Any idea if http://perldoc.perl.org/ will be updated with the docs for Perl 6?

Dash already has a Perl docset that's supported by me and I'd like to update that docset instead of adding a user-contributed one.

**Comment by davepagurek** [comment]
It's kind of a weird way of naming things because Perl 6 is an entirely separate language from Perl 5 and both will continue to be developed independently (think Python 2 and 3 split, but with the versions being even more different from each other.) http://dev.perl.org describes Perl 5 and 6 as "two languages in the Perl family, but of different lineages." 

So basically it's not just the next version of Perl, but a different language, although I'm not totally sure myself what is planned for the future of the Perl ecosystem.

**Comment by Kapeli** [comment]
Hmm. Not sure what to do really. I'll accept your docset for now. Thank you! :+1:

**Comment by Kapeli** [comment]
One note: I've renamed the docset to "Perl 6" (https://github.com/Kapeli/Dash-User-Contributions/commit/3b1830847eb487dede3605efb60d8963cf0407e7). If this isn't appropriate please let me know and I'll change it back.

**Comment by davepagurek** [comment]
ok by me  :+1:

**Pull request merged**
