### PR TITLE
Add a docset for Packer (https://packer.io)

### PR DESCRIPTION
**Pull request by dazoakley**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by dazoakley** [comment]
My pleasure, thanks for such a useful asap! :)

**Comment by dazoakley** [comment]
Gah, app! (Damn auto correct)

**Comment by amirrustam** [comment]
This does not work at all for me. Running the latest Dash. None of the links work and Dash search does not open up document pages.

**Comment by Kapeli** [comment]
Seems to work fine over here. What error(s) do you get? Can you add a screenshot? Have you tried reinstalling the docset?

**Comment by amirrustam** [comment]
Here is a video of what I'm seeing: https://dl.dropboxusercontent.com/u/122397/Dash_Packer_docset.mp4

And yes, I did reinstall it. I'm hoping it's just minor error on my part.

**Comment by Kapeli** [comment]
Do you have an Internet connection? As far as I can tell, this docset shouldn't work while offline as it loads some things (CSS) from the Internet.

**Comment by amirrustam** [comment]
Got a solid connection. I investigate further by drilling down into the docset package, and every html documentation file is the same. They all have proper names, but they all have same content, and content being the index page.

**Comment by Kapeli** [comment]
That's really weird. The HTML files definitely contain something on my end and are not the same.

Try this:
1. Download the docset from http://london2.kapeli.com/feeds/zzz/user_contributed/build/Packer/Packer.tgz
2. Unarchive it
3. Look inside it and open an HTML page in your regular browser. Does the same thing happen?

**Comment by amirrustam** [comment]
I downloaded it > unarchived it > "Show Package Contents" of Packer.docset
Same thing as before, all files have the same content (all have contents of index.html).
I event checked the files with a text editor to rule out any browser paranoia.

How is this even possible?

**Comment by Kapeli** [comment]
No idea. Can you re-archive the docset (preferably use zip or something different from tar) and upload it somewhere?

Are you behind a firewall with content filtering/protection or something like that?

**Comment by Kapeli** [comment]
Also... what OS X version are you using? Run this in Terminal:

```
/usr/bin/bsdtar --version
```

**Comment by amirrustam** [comment]
Yosemite 10.10.2
`bsdtar 2.8.3 - libarchive 2.8.3`

Every other docset including other user contributed docsets work just fine.
I'm not behind any fancy firewall. Regular home internet with your run-of-the-mill router.

**Comment by Kapeli** [comment]
That's same as me. Please do the re-archive and upload thingy.

**Comment by amirrustam** [comment]
Zipped it: https://dl.dropboxusercontent.com/u/122397/Packer.docset.zip

**Comment by Kapeli** [comment]
And... it works. Are you sure the HTML files are the same on your end when you open in an editor? They're similar at the beginning due to the menu, but the content is definitely different.

**Comment by amirrustam** [comment]
@Kapeli I'm sorry for wasting your time. If I would just have scrolled down further (though it is a bit misleading!). This is why I shouldn't stay up till 3AM coding. I'll show myself out now.

**Comment by Kapeli** [comment]
Still, that doesn't explain why the CSS doesn't load... Are you able to access http://packer.io/assets/stylesheets/application-dfcc9ac6.css in your browser?

**Comment by amirrustam** [comment]
screenshot 2015-04-04 03 29 22

**Comment by Kapeli** [comment]
Must be something wrong with their CDN...

@dazoakley Any chance you could update the docset so that it loads the CSS from a local file instead of going online?

**Comment by amirrustam** [comment]
No problem. I just did a test for the index page (screenshot), but I will send you a pull request when I apply the styling to all the docset.
screenshot 2015-04-04 03 41 36

**Comment by dazoakley** [comment]
Hi ya,

Sorry about this, I thought the package had included all of the site content (CSS, images and all).  I'll get an update built and push something your way later today. :)

Daz

**Comment by dazoakley** [comment]
I'll check my Terraform package too - I made that with essentially the same code so it probably has the same problem.

**Comment by amirrustam** [comment]
@dazoakley sounds great. Thanks.

**Pull request merged**
