### PR TITLE
Bump React to 0.13.1

### LINKED ISSUE #388: React docset out of date
@chenglou can you please update the React docset?

### PR DESCRIPTION
**Pull request by chenglou**
Fixes #388 
Fixes https://github.com/chenglou/react-dash/issues/3

### CODE REVIEW

**Comment by Kapeli** [comment]
Why not bump the main version as well and update the docset for it too? (i.e. https://github.com/chenglou/Dash-User-Contributions/commit/242e635a2989c8ccae75f3a89efa25225fe59bef#diff-36da890e41d83b8a35db4fd97bbe4088R3 and update docset in /React.tgz). Should I do it?

**Comment by chenglou** [comment]
Oops, forgot that spot. Fixed.

**Comment by Kapeli** [comment]
Just a note: it's not enough to add the docset in the `versions` folder, you also need to copy the docset in the root folder of your project. In other words, there should be a docset at this path: `docsets/React/React.tgz`. Otherwise, you just bump the version but the main docset remains the same old one.

I'll fix things this time.

**Comment by chenglou** [comment]
Crap, I've been doing it wrong. Thanks for the notice!

**Pull request merged**
