### PR TITLE
Update SDL from 2.0.8 to 2.0.10.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
I now have the index page set:
https://kapeli.com/docsets#settingindexpage

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
Is it because I am missing the `.dsidx`? https://kapeli.com/docsets#createsqlite

Does this generate it?
```DISABLE_INDEX     = YES```

**Comment by ryanpcmcquen** [comment]
I see the step here to generate it:
`CREATE TABLE searchIndex(id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT);`
But don't I need to create an SQLite DB in the first place?

**Comment by ryanpcmcquen** [comment]
https://github.com/Kapeli/Dash-User-Contributions/pull/2499

@superzazu, mind helping me out? I am having trouble creating the index.

**Comment by superzazu** [comment]
Hello, the .dsidx file is a SQLITE database that can be automatically generated by docsetutil. I opened a PR for the docset 2.0.10 update (!2054).

**Comment by ryanpcmcquen** [comment]
@superzazu, thank you! I thought `docsetutil` was removed from XCode, my machine doesn't have it ...

**Comment by superzazu** [comment]
`docsetutil` was indeed removed from Xcode a couple of versions back (see https://kapeli.com/docsets#doxygen). The workaround for now is using the old `docsetutil` binary that can be found [here](https://github.com/Kapeli/Dash-User-Contributions/pull/1884#issuecomment-389793784).

**Pull request closed without merging**
