### PR TITLE
Add docset for seaborn 0.12.1

### PR DESCRIPTION
**Pull request by paw-lu**
Add docset for seaborn 0.12.1.

This pull request was generated by [paw-lu/seaborn-dash-docset](https://github.com/paw-lu/seaborn-dash-docset).

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! ❤️

**Comment by Kapeli** [comment]
One slight issue: please use the "Seaborn" directory in the future, so that Dash knows to update the users that currently have seaborn installed to the latest version.

**Comment by paw-lu** [comment]
Ah good catch. Let me run this again later and target the `/Seaborn` directory. Should we delete `/seaborn`?

**Comment by Kapeli** [comment]
I've deleted `seaborn`. Everything should be ok now.

**Pull request merged**
