### PR TITLE
Add Cassandra and CQL docsets.

### PR DESCRIPTION
**Pull request by gebing**
Add Cassandra and CQL docsets.

### CODE REVIEW

**Comment by Kapeli** [comment]
The `Info.plist` inside the docsets need to be named exactly `Info.plist` (case-sensitive). Currently your docsets contain a file called `info.plist`.

**Comment by gebing** [comment]
I change the info.plist to Info.plist in docsets and commit again. pls check it again.

**Comment by Kapeli** [comment]
Failed validation:

```
Checking Cassandra/Cassandra.tgz...
File not found at "https://www.datastax.com" for entry with row id "1" of "Cassandra.docset"
File not found at "https://academy.datastax.com/" for entry with row id "2" of "Cassandra.docset"
File not found at "/en" for entry with row id "3" of "Cassandra.docset"
File not found at "https://www.datastax.com/contactus" for entry with row id "4" of "Cassandra.docset"
File not found at "https://academy.datastax.com/downloads" for entry with row id "5" of "Cassandra.docset"
File not found at "https://support.datastax.com/" for entry with row id "7" of "Cassandra.docset"
Found entry with new line in its name at row id "8" at "Cassandra.docset". Complete entry name is: "DEVELOPER
                        BLOGS"
File not found at "https://www.datastax.com/dev/blog/" for entry with row id "8" of "Cassandra.docset"
File not found at "https://www.apache.org/" for entry with row id "257" of "Cassandra.docset"
Checking CQL/CQL.tgz...
File not found at "https://www.datastax.com" for entry with row id "1" of "CQL.docset"
File not found at "https://academy.datastax.com/" for entry with row id "2" of "CQL.docset"
File not found at "/en" for entry with row id "3" of "CQL.docset"
File not found at "https://www.datastax.com/contactus" for entry with row id "4" of "CQL.docset"
File not found at "https://academy.datastax.com/downloads" for entry with row id "5" of "CQL.docset"
File not found at "https://support.datastax.com/" for entry with row id "7" of "CQL.docset"
Found entry with new line in its name at row id "8" at "CQL.docset". Complete entry name is: "DEVELOPER
                        BLOGS"
File not found at "https://www.datastax.com/dev/blog/" for entry with row id "8" of "CQL.docset"
File not found at "https://www.apache.org/" for entry with row id "165" of "CQL.docset"
```

**Comment by gebing** [comment]
Fixed and commit again.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
