### PR TITLE
Update powershell docset to v0.6

### PR DESCRIPTION
**Pull request by lucasg**
Powershell docset now package windows 10 powershell modules (
appx, hyper-v, smbshare, etc.) documentation.

### CODE REVIEW

**Comment by Kapeli** [comment]
Your docset's `docSet.dsidx` points to files that don't exist. See https://travis-ci.org/Kapeli/Dash-User-Contributions/builds/387441581 for the full log.

**Comment by Kapeli** [comment]
There are still entries that point to missing files. See https://travis-ci.org/Kapeli/Dash-User-Contributions/builds/387932812 for the log.

**Comment by lucasg** [comment]
Yeah sorry, I've finally located the issue : some resources I scrape have changed their DOM. I should put an updated docset at the end of the week.

**Comment by lucasg** [comment]
weird, the check is still failing :

```
Checking Powershell/Powershell.tgz...
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\CimCmdlets.html" for entry with row id "1" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Export-BinaryMiLog.html" for entry with row id "2" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Get-CimAssociatedInstance.html" for entry with row id "3" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Get-CimClass.html" for entry with row id "4" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Get-CimInstance.html" for entry with row id "5" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Get-CimSession.html" for entry with row id "6" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Import-BinaryMiLog.html" for entry with row id "7" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Invoke-CimMethod.html" for entry with row id "8" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\New-CimInstance.html" for entry with row id "9" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\New-CimSession.html" for entry with row id "10" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\New-CimSessionOption.html" for entry with row id "11" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Register-CimIndicationEvent.html" for entry with row id "12" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Remove-CimInstance.html" for entry with row id "13" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Remove-CimSession.html" for entry with row id "14" of "Powershell.docset"
File not found at "docs.microsoft.com\en-us\powershell\module\CimCmdlets\Set-CimInstance.html" for entry with row id "15" of "Powershell.docset"
...
```

However they are very present in the archive :

image


do you have a linux/windows version of `docsetcontrib` lying around ? That way I can test on my end why the build still fail.

**Comment by Kapeli** [comment]
I think the issue is that you're using `\` (Windows directory separator) instead of `/`.

Your paths should be: `docs.microsoft.com/en-us/powershell/module/CimCmdlets/CimCmdlets.html`

> do you have a linux/windows version of docsetcontrib lying around ? That way I can test on my end why the build still fail.

I don't, sorry.

**Comment by lucasg** [comment]
finally ! Sorry it took so long to fix it, it was the first time I did the packaging on a Windows machine.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
