### PR TITLE
Added docs for Eigen version 3.2.7

### PR DESCRIPTION
**Pull request by elrnv**
Updated the Info.plist file in both versions to have "eigen" as the dash keyword.
Updated the README.md and docset.json to reflect the version update.
NOTE: The binary in the Eigen directory is the same as what's in versions/3.2.7/

### CODE REVIEW

**Comment by Kapeli** [comment]
There's no point in having docsets in the `versions` if you don't have a `specific_versions` in your `docset.json` (https://github.com/Kapeli/Dash-User-Contributions/blob/master/Sample_Docset/docset.json#L14-L26). Either add the `specific_versions` or remove the docsets from `versions`.

**Comment by elrnv** [comment]
I'm not sure why the build failed here. It seems like it failed at the 3.2.4 version. I copied that docset directly from the current Eigen docset (what's currently on Dash), and only changed a few things in the Info.plist file. It works fine when I load it onto Dash from my machine.
Any hints on what I can do to make it work?

**Comment by Kapeli** [comment]
The 3.2.4 docset is an archived docset that was re-archived by you. Look in the Resources folder and you'll see there are no HTML files there. This means that this docset was installed by Dash at some point and you copied it over. You shouldn't do that.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by elrnv** [comment]
My pleasure! BTW this resolves #754 :)

**Pull request merged**
