### PR TITLE
confluent-kafka-python v1.0.3 docset

### PR DESCRIPTION
**Pull request by benbenbang**
Add a new docset for `confluent-kafka-python` v1.0.3

### CODE REVIEW

**Comment by Kapeli** [comment]
You need to add the archives as `.tgz`, not `.tgz.txt`.

**Comment by benbenbang** [comment]
> You need to add the archives as `.tgz`, not `.tgz.txt`.

The problem was when I add it as `.tgz` I couldn't pass the test, any idea on it? Thanks

**Comment by benbenbang** [comment]
Done, thanks

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
