### PR TITLE
PR for Bokeh 2.0.1 and Altair 4.1.0 

### PR DESCRIPTION
**Pull request by capac**
Updated docs for the Altair and Bokeh visualization packages.

### CODE REVIEW

**Comment by capac** [comment]
I don't understand the reason for the conflicting files this times, I haven't touched the files at all.

**Comment by Kapeli** [comment]
Please try to redo your fork.

**Comment by capac** [comment]
Do you have an idea why this error keeps showing up? I don't want it to reappear the next time I make a PR.

**Comment by Kapeli** [comment]
I don't, sorry. I do rewrite git history when I process a docset, but that doesn't seem to cause any issues with any other pull requests.

**Pull request closed without merging**
