### PR TITLE
Added "IBM_Maximo_Javadocs" docset

### PR DESCRIPTION
**Pull request by reedand**
Hi: I've added a new docset named "IBM_Maximo_Javadocs" for the IBM Maximo system.  Hopefully there's not but if there's anything I've missed, please let me know.  Thanks.

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by reedand** [comment]
Hi: Thanks for that.  Unfortunately I think there is a problem with the docset I added.  The error I get is: an error occured while installing the docset. The error message is: 

Unable to extract docset archive. Exit code: 1.

Check your Internet connection and free disk space and try again. Please contact Dash's developer if you cannot recover from this error.

**Comment by Kapeli** [comment]
This was due to an issue on my end. I've fixed it. Sorry for the inconvenience!

**Comment by reedand** [comment]
Thanks for your help and the quick response.

**Pull request merged**
