### PR TITLE
rename scikit to scikit-learn

### PR DESCRIPTION
**Pull request by sciunto**
I fixed the path for scikit-learn. Thanks.

### CODE REVIEW

**Comment by Kapeli** [comment]
This would cause Dash to treat this docset as a new one and all users that have the docset installed won't get updates anymore. Sorry.

**Comment by sciunto** [comment]
That's sad, the naming is just wrong. :(

**Comment by Kapeli** [comment]
The naming only affects this repo and not end-users, so it's fine.

**Comment by sciunto** [comment]
Not really. I'm discovering all the work around dask, but for instance, here: https://github.com/zsoltika/feeds the xml file has a wrong name.

**Pull request closed without merging**
