### PR TITLE
add bluebird docset

### PR DESCRIPTION
**Pull request by giladgray**
Docset for Bluebird promises library https://github.com/petkaantonov/bluebird.

Major feature missing here is Lodash-style table of contents where headings are the document sections (Array, Collection, Object, etc). I couldn't figure out how to do this, is such a thing possible in user-contributed docsets? Right now, all the Bluebird functions live under the heading "Functions" which isn't very useful for navigation.

### CODE REVIEW

**Comment by Kapeli** [comment]
It is possible, but not documented.

First, change your `DashDocSetFamily` to `dashtoc2`.

Then inside the pages add anchors like this:

```html
For sections:
<a class="dashAnchor" name="//dash_ref/Function/String%20Functions/1"></a>

For entries:
<a class="dashAnchor" name="//dash_ref/Function/escape/0"></a>
```

The difference between sections and anchors is basically the `/1` and `/0` at the end.

**Comment by giladgray** [comment]
Ah cool! So when it's time for a new section I do a `/1` anchor? Like, `<h2>`s get `/1` anchors and `<h5>`s get `/0`s?

**Comment by Kapeli** [comment]
Exactly. Good job!

There are 2 issues remaining:
1. In the docSet.dsidx all the entries for `id` are NULL. This is not a huge issue, its only side effect is that Dash can't count how many entries there are for a type. If possible, please fix it. I've seen this before with docsets that were generated using Node.js. Maybe Node.js doesn't fill the primary key automatically or you need to do something special to set `id` as primary key?
2. In the table of contents, there are 2 sections that have no entries in them: `Progression migration` and `Deferred migration`. If possible, please add a fake section entry in them, even if you duplicate things it's fine. You should have something like this:

```html
<a name="//dash_ref/Section/Deferred%20migration/1" class="dashAnchor"></a>
<a name="//dash_ref/Section/Deferred%20migration/0" class="dashAnchor"></a>
```

**Comment by giladgray** [comment]
1. That was weird. Turns out all I had to do was add `primaryKey: true` to the Sequelize `id` definition.
2. Ah yeah that's awkward. Shimmed those extra `/0` anchors in there.

Now I'm just going to fix some broken links and get this ready to rock!

**Comment by Kapeli** [comment]
Great! Did you get a chance to fix the broken links? Is this ready to merge?

**Comment by giladgray** [comment]
Yes I did, every link works as expected. Ready to merge!

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by giladgray** [comment]
My pleasure! I'm going to create a yeoman generator out of my little docset repo so I can do this more often, I'll keep you posted :smile:

**Comment by Kapeli** [comment]
:heart_eyes:

**Pull request merged**
