### PR TITLE
Commit PyMel Docset

### PR DESCRIPTION
**Pull request by alexwidener**
PyMel 1.0.7 Initial commit

### CODE REVIEW

**Comment by alexwidener** [comment]
I have no idea what that means. I looked at the details. Can I get an explanation?

**Comment by Kapeli** [comment]
The error is: `icon.png` must be `16x16` in size. `icon@2x.png` must be `32x32` in size.

**Comment by alexwidener** [comment]
Thanks, it wasn't showing that anywhere.
Should be fixed now!

**Comment by Kapeli** [comment]
Looks good. One more issue: why did you include the docsets inside `versions` folders too? You don't need to do that unless you're using the `specific_versions` in docset.json (which you aren't).

**Comment by alexwidener** [comment]
Because I planned on updating them. Blender updates moderately frequently and PyMel updates yearly. It's pretty common for people to be on older versions in studios, so if someone grabs it next year, they'd be caught up. Want me to remove them until then?

**Comment by Kapeli** [comment]
Either remove them until then, or add the appropriate entries under `specific_versions`. It's ok to have just 1 entry inside `specific_versions`, so there's no need to hide them until then.

**Comment by alexwidener** [comment]
Hi Bogdan, is there anything else holding this up or can it be merged and closed? 
Thanks!

**Comment by Kapeli** [comment]
Looks good. Sorry for the wait. GitHub doesn't send notifications when you add a commit, so I didn't notice you fixed things until you commented just now.

**Pull request merged**
