### PR TITLE
add Ionic docset

### PR DESCRIPTION
**Pull request by DarkSwoop**
this is the docset for ionicframework.com

### CODE REVIEW

**Comment by hootsieroll** [comment]
This is so great, thanks for the effort.  How tough would it be to update to beta-14?

**Comment by DarkSwoop** [comment]
@hootsieroll https://github.com/Kapeli/Dash-User-Contributions/pull/340 :wink:

**Comment by hootsieroll** [comment]
@DarkSwoop Thanks!

**Comment by kapilpa** [comment]
can anyone upload the ionic docset ... am on windows using zeal

**Comment by yevmel** [comment]
can not see the doclet. am i missing something?

nothing-found

**Comment by Kapeli** [comment]
See https://github.com/DarkSwoop/dash-ionic/issues/2.

**Comment by yevmel** [comment]
@Kapeli awesome! thx.

**Comment by viniciussbs** [comment]
Is this "official" version available only for Dash 3? I'm using Dash 2 and I still can't find it.

**Comment by Kapeli** [comment]
Yes. Ionic is only available in Dash 3.

**Comment by viniciussbs** [comment]
And Dash 3 is a paid upgrade for who purchased Dash 2?

**Comment by Kapeli** [comment]
Yes. The upgrade to Dash 3 costs $10.

**Pull request closed without merging**
