### PR TITLE
Add Bullet docset

### PR DESCRIPTION
**Pull request by caseywebdev**
Hopefully I did this right :wink:

### CODE REVIEW

**Comment by caseywebdev** [comment]
Hmm, build failed. Guess it's not right? Any help would be appreciated.

**Comment by caseywebdev** [comment]
I think I found the problem, working on a fix.

**Comment by caseywebdev** [comment]
There we go. For reference, you can't have an unescaped `&` in the Doxygen `PROJECT_NAME`.

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by caseywebdev** [comment]
No prob, thanks for merging!

**Comment by caseywebdev** [comment]
@Kapeli how can we change the default keyword to `bullet:` instead of `doxygen:`?

screen shot 2015-09-30 at 3 54 14 pm

**Comment by Kapeli** [comment]
Edit the docset's Info.plist and set `DashDocSetKeyword` to the keyword you want.

**Comment by caseywebdev** [comment]
Gotcha, I'll open a new PR.

**Pull request merged**
