### PR TITLE
add statsmodels documentation

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by bendichter** [comment]
Does this error mean that a retina icon is required?

**Comment by Kapeli** [comment]
Yes.

Include a icon.png and icon@2x.png with sizes exactly 16x16 and 32x32.

**Comment by Kapeli** [comment]
Your icons are not 16x16 and 32x32, but 32x32 and 64x64.

**Comment by bendichter** [comment]
Does this PR fulfill all of the requirements? I'd like to contribute more docs that I think would be useful for the community, but I want to make sure I have the workflow down first.

**Comment by Kapeli** [comment]
Yes. Thank you!

Sorry for the wait, I missed your last icon change commit.

**Pull request merged**
