### PR TITLE
Update and improve scikit-learn docs

### PR DESCRIPTION
**Pull request by jnothman**
* Update from 0.19.0 to 0.19.1
* Use recent doc2dash custom parser feature to enhance docs
    * add user guides to TOC
    * prefix some user guide titles to indicate structure and subtypes
    * remove attributes from TOC as not consistently exported by
      numpydoc/doc2dash at present
* Add index page
* Add a build script to automatically acquire and build docs for a given version tag, and package them in preparation for committing to Dash-User-Contributions

### CODE REVIEW

**Comment by jnothman** [comment]
I'm attempting something that might reduce the size. Please wait before merging.

**Comment by jnothman** [comment]
Ping @jaypeedevlin

**Comment by jnothman** [comment]
Btw, @kapeli, other doc2dash sphinx projects (including numpy, scipy, pandas and matplotlib for which there are official docsets) would benefit greatly from having user guides displayed as configured here (espeically matplotlib and pandas, IMO, which use a lot of examples and narrative documentation).

**Comment by Kapeli** [comment]
Thank you! 👍 

Thanks for the Guides tip. I'll update the docsets I maintain ASAP.

**Comment by jnothman** [comment]
> Thanks for the Guides tip. I'll update the docsets I maintain ASAP.

Looks much better! I think matplotlib would benefit from having example titles prefixed with "Example:" as is done here, otherwise the Guides listing is a very mixed bag. (Or add an example Type.)

**Pull request merged**
