### PR TITLE
Add XCTest docset for UI Testing in Xcode 7

### PR DESCRIPTION
**Pull request by joemasilotti**

### CODE REVIEW

**Comment by Kapeli** [comment]
Did you archive the wrong docset? I get an empty `Sample_Docset.docset` after unarchiving `XCTest.tgz`.

**Comment by joemasilotti** [comment]
Ah, sorry about that. I updated the archive, please try again.

**Comment by Kapeli** [comment]
Looks good. 2 more issues:

1. Add a `DocSetPlatformFamily` key in the docset's Info.plist with a value of `xctest`
2. Change the name in the `docset.json` to just `XCTest`

**Comment by joemasilotti** [comment]
Cool. Done and done!

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by joemasilotti** [comment]
Awesome, happy to help!

**Pull request merged**
