### PR TITLE
Add FreeBSD

### PR DESCRIPTION
**Pull request by publicarray**

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:
```
Checking FreeBSD_Handbook/freebsd.tgz...
Found entry with new line in its name at row id "30" at "freebsd.docset". Complete entry name is: "Intended
  Audience"
Found entry with new line in its name at row id "31" at "freebsd.docset". Complete entry name is: "Changes
    from the Third Edition"
Found entry with new line in its name at row id "32" at "freebsd.docset". Complete entry name is: "Changes
    from the Second Edition (2004)"
Found entry with new line in its name at row id "33" at "freebsd.docset". Complete entry name is: "Changes from
    the First Edition (2001)"
Found entry with new line in its name at row id "35" at "freebsd.docset". Complete entry name is: "Conventions used
    in this book"
Found entry with new line in its name at row id "51" at "freebsd.docset". Complete entry name is: "30.10. Common Address Redundancy Protocol
	(CARP)"
Found entry with new line in its name at row id "84" at "freebsd.docset". Complete entry name is: "17.14. Highly Available Storage
	(HAST)"
Found entry with new line in its name at row id "116" at "freebsd.docset". Complete entry name is: "18.4. RAID3 - Byte-level Striping with
	Dedicated Parity"
Found entry with new line in its name at row id "125" at "freebsd.docset". Complete entry name is: "13.7. VPN over
	IPsec"
Found entry with new line in its name at row id "129" at "freebsd.docset". Complete entry name is: "14.6. Managing Jails with
	ezjail"
Found entry with new line in its name at row id "143" at "freebsd.docset". Complete entry name is: "Chapter 22. Localization -
      i18n/L10n Usage and
      Setup"
Found entry with new line in its name at row id "172" at "freebsd.docset". Complete entry name is: "A.1. CD and
      DVD Sets"
Found entry with new line in its name at row id "182" at "freebsd.docset". Complete entry name is: "28.6. Dynamic Host Configuration Protocol
      (DHCP)"
Found entry with new line in its name at row id "186" at "freebsd.docset". Complete entry name is: "28.2. The inetd
      Super-Server"
Found entry with new line in its name at row id "188" at "freebsd.docset". Complete entry name is: "28.12. iSCSI Initiator and Target
      Configuration"
Found entry with new line in its name at row id "189" at "freebsd.docset". Complete entry name is: "28.5. Lightweight Directory Access Protocol
	(LDAP)"
Found entry with new line in its name at row id "191" at "freebsd.docset". Complete entry name is: "28.4. Network Information System
      (NIS)"
Found entry with new line in its name at row id "194" at "freebsd.docset". Complete entry name is: "28.10. File and Print Services for Microsoft® Windows® Clients
      (Samba)"
Found entry with new line in its name at row id "208" at "freebsd.docset". Complete entry name is: "4.4. Using pkg for Binary Package
      Management"
Found entry with new line in its name at row id "213" at "freebsd.docset". Complete entry name is: "4.6. Building Packages with
      Poudriere"
Found entry with new line in its name at row id "220" at "freebsd.docset". Complete entry name is: "26.5. Using PPP over
      ATM (PPPoA)"
Found entry with new line in its name at row id "239" at "freebsd.docset". Complete entry name is: "27.3. Sendmail Configuration
	Files"
Found entry with new line in its name at row id "266" at "freebsd.docset". Complete entry name is: "21.2. FreeBSD as a Guest on Parallels for
      Mac OS® X"
Found entry with new line in its name at row id "268" at "freebsd.docset". Complete entry name is: "21.3. FreeBSD as a Guest on Virtual PC
      for Windows®"
Found entry with new line in its name at row id "269" at "freebsd.docset". Complete entry name is: "21.4. FreeBSD as a Guest on VMware Fusion
      for Mac OS®"
Found entry with new line in its name at row id "270" at "freebsd.docset". Complete entry name is: "21.7. FreeBSD as a Host with
      bhyve"
Found entry with new line in its name at row id "271" at "freebsd.docset". Complete entry name is: "21.6. FreeBSD as a Host with
      VirtualBox"
```

**Comment by publicarray** [comment]
The problem is with this html:

```html
<h2 xmlns="http://www.w3.org/1999/xhtml" class="title" style="clear: both"><a id="jails-ezjail"></a>14.6. Managing Jails with
	<span class="application">ezjail</span></h2>
```

I tried fixing it with reqexp in the `dashing.json` but I'm having no luck.

```json
{
    "name": "FreeBSD Handbook",
    "package": "freebsd",
    "index": "index.html",
    "selectors": {
        "h1": "Guide",
        "h2": [
            {
                "type": "Section",
                "regexp": "\n<[^h2]{0,}>(.*)<[^h2]{0,}>",
                "replacement": " $1"
            }
        ]
    },
    "icon32x32": "icon.png",
    "allowJS": false,
    "ExternalURL": "https://www.freebsd.org/doc/en/books/handbook/"
}
```

**Comment by publicarray** [comment]
nvm I figured it out

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
