### PR TITLE
Add QGIS docset

### PR DESCRIPTION
**Pull request by troopa81**
Add QGIS API docset for version 3.4.2

QGIS (http://qgis.com/) is an opensource widely used GIS (Geographic Information System) application that could be extended thanks to this API.

I cannot push the tgz file because its size (470M) exceed the github limits. Please let me know how I can send you these file.

Regards
Julien

### CODE REVIEW

**Comment by Kapeli** [comment]
Upload it wherever you can (e.g. Dropbox) and give me a link.

**Comment by troopa81** [comment]
Here is the link : https://www.dropbox.com/s/qyvdshe9pv1oyvl/QGIS.tgz?dl=0

**Comment by Kapeli** [comment]
The docset is not valid.

As far as I can tell, it's missing the "isDashDocset" key in Info.plist. See https://kapeli.com/resources/Info.plist for a sample Info.plist.

**Comment by troopa81** [comment]
Is there anyway I can test the Docset to check if it's valid without being on a Mac ? The docset is working with Zeal.

Anyway, I made the modifications to the Info.plist file, hope it will be enough. 

here is a new link : https://www.dropbox.com/s/c3txcr4u7560bbm/QGIS.tgz?dl=0

**Comment by Kapeli** [comment]
All good now. 

> Is there anyway I can test the Docset to check if it's valid without being on a Mac 

No, sorry. The docset checker also requires Mac.

**Pull request merged**
