### PR TITLE
Initial Commit for Redux v3.4.0

### PR DESCRIPTION
**Pull request by epitaphmike**
First pass at the Redux Documentation.

### CODE REVIEW

**Comment by Kapeli** [comment]
There are some issues with the table of contents.

screen shot 2016-04-19 at 10 56 56

**Comment by epitaphmike** [comment]
I updated the TOC Sections. I don't know if you've done it yet, but you can now squash commits!
https://github.com/blog/2141-squash-your-commits

**Comment by Kapeli** [comment]
One more issue: the TOC sections for the "Sample" entries show up as Properties. Is this intentional?

screen shot 2016-04-19 at 16 47 58

**Comment by epitaphmike** [comment]
Ugh. Not intentional. Late night. Early Morning. Thanks for the extra eyes!

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
