### PR TITLE
Update Terraform docsets and Improvement some features

### PR DESCRIPTION
**Pull request by f440**
Hi.

(CC: @dazoakley)

It seems to me that Terrafrom.docset stopped to follow the Terraform's release version. I'm trying to update it.

Improvement point:

- Optimized screen (remove header, sidebar and adjust screen size)
- Support TOC
- Better support terraform's items
- Generation from source code (currently: from official site by web crawling), so easy to customize and regenere to the latest version.

### CODE REVIEW

**Comment by Kapeli** [comment]
I've made some comments in the pull request. Apart from that, the only issue I see is with the TOC. If you search for "provider" you'll see in the TOC an entry show up as Unknown. This happens because the entry is `helper/schema`, but you did not percent-encode it. The anchor for it is:

```
<a class="dashAnchor" name="//apple_ref/cpp/Section/helper/schema"></a>
```

It should be:

```
<a class="dashAnchor" name="//apple_ref/cpp/Section/helper%2Fschema"></a>
```

**Comment by f440** [comment]
Thank you for comments. All your points are fixed.

**Comment by Kapeli** [comment]
Everything seems fine. Great job!

I'm going to go ahead and merge this. @dazoakley if you notice anything wrong or have any comments, let me know.

**Comment by dazoakley** [comment]
Looks good and thanks for taking this up @f440, i'm not really working with Terraform much these days so I don't hear about the new releases as often as I used too. :+1:

Only comments I can give:

* The "introduction and getting started guide" link on the homepage is broken.
* I'd prefer having the sidebar navigation back (this is just a personal preference - I tended to browse the docs that way as I was used to the terraform site), but it's up to you on that one.

**Comment by Kapeli** [comment]
> I'd prefer having the sidebar navigation back (this is just a personal preference - I tended to browse the docs that way as I was used to the terraform site), but it's up to you on that one.

The general approach I have with Dash is to hide the sidebars and provide navigation within Dash with appropriate indexing and so on. I don't impose this rule for user-generated docsets though, it's just a recommendation.

**Comment by dazoakley** [comment]
Ah cool, if that's the general approach with the other docsets I'm ok with
that. :)

**Comment by f440** [comment]
@dazoakley @Kapeli I appreciate your advice. Thank you!

> The "introduction and getting started guide" link on the homepage is broken.

It's my mistake, will fix in next release.

**Pull request merged**
