### PR TITLE
Update Zig 0.9.1 & add Zig 0.10.0-dev

### PR DESCRIPTION
**Pull request by puqeko**
- Adds the option of choosing a 0.10.0 development version.
- Now includes Zig Standard Library in 0.9.1 and 0.10.0.

Also:
- Add table of contents support
- Add online redirection support
- Include new entity types in index (types, builtins, keywords)
- Add parent header descriptions to Guides in search menu
- Unknown links go to online
- Zig Language Reference.html was edited to include specific dev version instead of 'master'

See #3921

puqeko@gmail.com

### CODE REVIEW

**Comment by puqeko** [comment]
@kassane may wish to review?

**Comment by kassane** [comment]
> @kassane may wish to review?

Nice. I'm testing it on my machine and it's working.

I would suggest keeping the main folder name `zig.docset` changing only the content version.

**Comment by kassane** [comment]
LGTM!

**Comment by Kapeli** [comment]
Thank you! ❤️

**Pull request merged**
