### PR TITLE
Update Raspberry Pi Pico SDK to 1.2.0

### PR DESCRIPTION
**Pull request by cesarvandevelde**
This pull request updates the docset from 1.0.1 to 1.1.2.
Additionally, the docset now includes a table of contents on each page.
The updated generator script can be found [here](https://github.com/cesarvandevelde/pico-sdk-docset).

### CODE REVIEW

**Comment by cesarvandevelde** [comment]
A new version of the SDK was released yesterday, so I updated the docset as well...

**Comment by Kapeli** [comment]
Sorry for the wait!

Unfortunately this fails validation:

```
Checking Raspberry_Pi_Pico_SDK/Raspberry_Pi_Pico_SDK.tgz...
Could not find docset after unarchiving "/Users/bogdan/Desktop/3311/docsets/Raspberry_Pi_Pico_SDK/Raspberry_Pi_Pico_SDK.tgz"
Checking Raspberry_Pi_Pico_SDK/versions/1.1.2/Raspberry_Pi_Pico_SDK.tgz...
Could not find docset after unarchiving "/Users/bogdan/Desktop/3311/docsets/Raspberry_Pi_Pico_SDK/versions/1.1.2/Raspberry_Pi_Pico_SDK.tgz"
Checking Raspberry_Pi_Pico_SDK/versions/1.2.0/Raspberry_Pi_Pico_SDK.tgz...
Could not find docset after unarchiving "/Users/bogdan/Desktop/3311/docsets/Raspberry_Pi_Pico_SDK/versions/1.2.0/Raspberry_Pi_Pico_SDK.tgz"
```

This happens because the archive needs to contain only the docset within and no other folders. Currently the archive contains the following dir structure: `Users/cesar/git-repos/pico-sdk-docset`.

**Comment by cesarvandevelde** [comment]
This should be fixed now. I recently updated the generator script to create the tar file automatically, but this created the wrong archive structure due to the use of absolute paths. The generator script has been updated to fix this problem.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
