### PR TITLE
Add Salesforce Apex docset

### PR DESCRIPTION
**Pull request by jairzh**

### CODE REVIEW

**Comment by Kapeli** [comment]
Errors:

```
Not 16x16: "icon.png" in "Apex"
Not 32x32: "icon@2x.png" in "Apex"
Checking Apex/Apex.tgz...
Found directory in main index: Entry with row id "886" and path "" at "apex.docset"
Found directory in main index: Entry with row id "890" and path "" at "apex.docset"
Found directory in main index: Entry with row id "899" and path "" at "apex.docset"
Found directory in main index: Entry with row id "903" and path "" at "apex.docset"
Found directory in main index: Entry with row id "911" and path "" at "apex.docset"
Found directory in main index: Entry with row id "927" and path "" at "apex.docset"
Found directory in main index: Entry with row id "983" and path "" at "apex.docset"
Found directory in main index: Entry with row id "1000" and path "" at "apex.docset"
```

The "found directory" errors aren't really about directories. They show up because the paths are empty.

**Comment by jairzh** [comment]
How can I fix this issues?

**Comment by Kapeli** [comment]
You need  to stop adding entries that have empty paths to docSet.dsidx and you need to resize the icons to 16x16 and 32x32.

**Comment by jairzh** [comment]
Got it, thanks.

**Pull request closed without merging**
