### PR TITLE
Update pwntools and IntelASMx86

### PR DESCRIPTION
**Pull request by Kira-cxy**
## pwntools
3.12.0 --> 3.14.0dev
Note that the previous version is wrong. It's 3.14.0dev actually. So I didn't add the "3.12.0" folder.
## IntelASMx86
2018-5-20 --> 2018-12-22

I'm not sure wether my operations on the folders is right. If not, please correct me :)

### CODE REVIEW

**Comment by Kapeli** [comment]
You're not using `specific_versions` in your `docset.json`, so you shouldn't be using a `versions` folder. Just place the docset at the path specified in `docset.json` (i.e. `docsets/pwntools/pwntools.tgz` and `docsets/IntelASMx86/IntelASMx86.tgz`).

**Comment by Kira-cxy** [comment]
Sorry, I didn't know the rules. I added `specific_versions` in `docset.json` for further convenience.

**Comment by Kapeli** [comment]
`specific_versions` need to be sorted by newest-first.

Moving the `.tgz.txt` file doesn't do anything. You need to add an actual archive at this path: `versions/2018-05-20/IntelASMx86.tgz`.

You still need to add docsets for the main archives (`docsets/pwntools/pwntools.tgz` and `docsets/IntelASMx86/IntelASMx86.tgz`)

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
