### PR TITLE
Update Vulkan docs to 1.3.249

### PR DESCRIPTION
**Pull request by pthariensflame**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! ❤️

**Comment by antiagainst** [comment]
Thanks for the update! However, this changes the original doc style entirely---now all the spec is without the original vulkan spec theming and colors. E.g.:

Before: 
Screenshot 2023-05-02 at 4 45 19 PM

vs. after:
Screenshot 2023-05-02 at 4 45 40 PM

I'm not sure this is the way we want to go?

**Comment by pthariensflame** [comment]
Oops!

Feel free to send in a correct version, and maybe document how to do it?  I was attempting to go by the README, but it was very obviously out of date.

**Comment by antiagainst** [comment]
No worries! I've uploaded https://github.com/Kapeli/Dash-User-Contributions/pull/4290 for version 1.3.250 to fix this. :)

Yes good points. I'll update the README to reflect the current status.

**Pull request merged**
