### PR TITLE
Zimbra SOAP and Zimlet Modifications

### PR DESCRIPTION
**Pull request by wolfyzvf**
- Adding a new 32x32 icon
- Adding a new 16x16 icon
- Deleting the version number in the Info.list Name
- Adapting the docset.json to work with versioning

### CODE REVIEW

**Comment by wolfyzvf** [comment]
The automatic build doesn't seems to work as one of the file contain the "#" character on the Zimbra Zimlet API 8.6 docset

**Comment by Kapeli** [comment]
Try to percent-encode the `#`.

**Comment by wolfyzvf** [comment]
Is there any more requirements to meet ?

**Comment by Kapeli** [comment]
Looks good. By the way, I don't get notified when you add new commits, so in the future make sure to also comment on the pull request when it's ready to be merged.

**Pull request merged**
