### PR TITLE
Creation of Flow Docset

### PR DESCRIPTION
**Pull request by epitaphmike**

### CODE REVIEW

**Comment by epitaphmike** [comment]
Made correction to archive version

**Comment by epitaphmike** [comment]
An additional update to Relay. Update to version 0.3.1, Guide: Babel Plugin.

**Comment by Kapeli** [comment]
The docSet.dsidx inside Relay.docset is empty.

**Comment by epitaphmike** [comment]
Updated json with proper version order. Fixed error with empty docSet.disdx

**Comment by Kapeli** [comment]
Merged. Thank you! :+1:

**Comment by epitaphmike** [comment]
Sorry for the back and forth!

**Pull request closed without merging**
