### PR TITLE
Gforth Docset for Dash

### PR DESCRIPTION
**Pull request by bitmason**

### CODE REVIEW

**Comment by bitmason** [comment]
Source for docket is here:  https://github.com/bitmason/gforth-docset

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by bitmason** [comment]
Thanks for the fast merge, @Kapeli. I see there's an `img` directory that wasn't merged.  Maybe you didn't want it or it's non-conforming; dunno (my first contrib to Dash).  So you'll see a broken image link at the end of the public README now.

I can drop the reference in the README and give another pull request or you can add that [img](https://github.com/bitmason/gforth-docset/tree/master/img) folder with the one image in it.  BTW, it's non-essential, just a full-res of this particular GNU project's logo, which I also scale down to make the docket icons that *were* merged.  Lemme know.  Cheers.

**Comment by bitmason** [comment]
Gimme a bit and I'll fix that and also ... re/ versioning... I see, only now after it's been merged, how you append the "0.7.0" after the docset name in the docset listing in the App.  In the case of Gforth, this is unnecessarily cluttered (it's a mature project) so let me get rid of that level altogether.

I'll give a pull request in a bit.

**Comment by Kapeli** [comment]
You didn't include any `img` folder in your pull request. I'd recommend against including it anyways, as there's no need for the image in the README.

**Comment by bitmason** [comment]
Agreed. Thanks.

**Pull request merged**
