### PR TITLE
update tailwindcss to 1.4(.5) + make it even more offline!

### PR DESCRIPTION
**Pull request by godbout**
doc has been updated, and docset is cleaner now. got rid of useless JS and mostly everything is offline now (except unsplash images, at least for now).

### CODE REVIEW

**Comment by godbout** [comment]
just realized the google fonts after commit. so two commits.

**Comment by godbout** [comment]
seems there's a page missing. probably because there's two pages with the same name. will investigate.

**Comment by godbout** [comment]
ok so yeah it's due to the fact that i flatten what i download. in this case there's two pages that end up with the same name. i'll have to update my docset builder to handle that, then will publish an update version of this docset.

**Comment by godbout** [comment]
fixed 👍🏼️

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
