### PR TITLE
Add webpack v2.1.0-beta docset

### PR DESCRIPTION
**Pull request by silvenon**

### CODE REVIEW

**Comment by silvenon** [comment]
Please let me know if I can do something about the failing test.

**Comment by Kapeli** [comment]
The failure is because of this:

```
File not found at "loaders-html-loader.htmlundefined" for entry with row id "365" of "webpack.docset"
File not found at "loaders-html-loader.htmlundefined" for entry with row id "366" of "webpack.docset"
File not found at "loaders-html-loader.htmlundefined" for entry with row id "367" of "webpack.docset"
File not found at "loaders-html-loader.htmlundefined" for entry with row id "373" of "webpack.docset"
File not found at "loaders-html-loader.htmlundefined" for entry with row id "374" of "webpack.docset"
File not found at "loaders-json5-loader.htmlundefined" for entry with row id "403" of "webpack.docset"
File not found at "loaders-json5-loader.htmlundefined" for entry with row id "404" of "webpack.docset"
File not found at "loaders-json5-loader.htmlundefined" for entry with row id "405" of "webpack.docset"
File not found at "loaders-json5-loader.htmlundefined" for entry with row id "406" of "webpack.docset"
```

This means that you have entries in docSet.dsidx that point to files that do not exist inside the docset.

**Comment by silvenon** [comment]
Thanks, I realized what I did wrong, fixed! 🎉

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by silvenon** [comment]
@Kapeli when will this be made available?

**Comment by Kapeli** [comment]
What do you mean? It's available in Preferences > Downloads > User Contributed.

**Comment by silvenon** [comment]
@Kapeli oops, my bad! I was searching in "Main Docsets" 😅

**Pull request merged**
