### PR TITLE
Updated Kotlin docset to version 1.5.0

### PR DESCRIPTION
**Pull request by ikurek**
* Docset updated to latest Kotlin version 1.5.0
* Removed @pthariensflame from `author` field (sorry 😞 )

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by ikurek** [comment]
@Kapeli I've just read the readme, and I wonder if I qualify for a free license? 🤔 Mine is only valid for Dash 5, so getting one for Dash 6 would be nice 🙂

**Comment by Kapeli** [comment]
Sure. What's your email?

**Comment by ikurek** [comment]
> Sure. What's your email?

igorkurek96@gmail.com thank You! 🙂

**Pull request merged**
