### PR TITLE
Update to React-Native v0.53.0

### PR DESCRIPTION
**Pull request by vexus2**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by epitaphmike** [comment]
@vexus2 Thanks for taking this over! This repo (https://github.com/dash-docs-community/react-native-dash) was made to handle future changes if you want to contribute there?

**Comment by vexus2** [comment]
@epitaphmike Hi. If you give me Contributor's privileges, I will maintain the React Native's Dash document.

**Comment by epitaphmike** [comment]
@vexus2 You're good to go.

**Pull request merged**
