### PR TITLE
add Tailwind CSS 3.1.3

### PR DESCRIPTION
**Pull request by godbout**

### CODE REVIEW

**Comment by godbout** [comment]
checked through `docsetcontrib`.

**Comment by godbout** [comment]
oh, CI is back. cool.

**Comment by Kapeli** [comment]
Please remove the `unarchived_temp`

**Comment by godbout** [comment]
> Please remove the `unarchived_temp`

i was SURE i had removed it, not like last time. getting old i guess. thanks.

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by godbout** [comment]
does the new CI workflow runs the `docsetcontrib`? i'd like to avoid doing this manually in the future.

**Comment by Kapeli** [comment]
> does the new CI workflow runs the `docsetcontrib`? i'd like to avoid doing this manually in the future.

Yep

**Comment by godbout** [comment]
> > does the new CI workflow runs the `docsetcontrib`? i'd like to avoid doing this manually in the future.
> 
> Yep

fantastic thanks. no more `remove the unarchive_temp` messages for me. i was starting getting PTSD.

**Pull request merged**
