### PR TITLE
New version of Transformers docset - 2.9.1

### PR DESCRIPTION
**Pull request by venkatasg**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by tshu-w** [comment]
@venkatasg Hi, I tried to generate new version of Transformers docset, but I don't know how to get rid of the sidebar. I would like to ask you how to generate it.

Screen Shot 2021-01-18 at 9 36 49 PM

**Comment by venkatasg** [comment]
Hi @tshu-w, you can follow the steps I followed to produce the docset in its current form on [my fork](https://github.com/venkatasg/Dash-User-Contributions/tree/master/docsets/transformers). I use a `hidesidebar.css` file which you can find on that repo to hide the sidebar.

**Comment by tshu-w** [comment]
@venkatasg Hi, thanks for the quick reply, I'll take a look.

**Pull request merged**
