### PR TITLE
update Leaflet docset for v1.4.0

### PR DESCRIPTION
**Pull request by drewda**
from https://github.com/drewda/leaflet-docset/releases/tag/2019.01.30-1.4.0

fixes https://github.com/drewda/leaflet-docset/issues/1

### CODE REVIEW

**Comment by drewda** [comment]
@Kapeli let me know if there are any changes you recommend.

**Comment by Kapeli** [comment]
Can you drop the `./` prefix from your paths in docSet.dsidx?

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by drewda** [comment]
And thank you!

BTW, do you have any suggestions for how I can improve or simplify the process within https://github.com/drewda/leaflet-docset ? I guess it's no longer relevant for me to be attaching docset files to each release on that repo.

**Comment by Kapeli** [comment]
That's up to you really, if you want to maintain a separate docset feed alongside contributing the docset here.

**Pull request merged**
