### PR TITLE
Kafka 0.8.2 docset

### PR DESCRIPTION
**Pull request by Igosuki**
Was able to untar a newly made archive with the same command as dash', don't know what went wrong previously.

### CODE REVIEW

**Comment by Kapeli** [comment]
The issues are:

```
Found entry with new line in its name at row id "40" at "kafka.docset". Complete entry name is: "Mirroring data between
                    clusters"
Found entry with new line in its name at row id "41" at "kafka.docset". Complete entry name is: "Expanding your
                    cluster"
Found entry with new line in its name at row id "42" at "kafka.docset". Complete entry name is: "Decommissioning
                    brokers"
Found entry with new line in its name at row id "43" at "kafka.docset". Complete entry name is: "Increasing
                    replication factor"
```

Unarchival issue: no idea. Can you archive using the same way as you archived Kafka/versions/0.8.2/kafka.tgz? That one seems to work.

**Comment by Igosuki** [comment]
The archive at the root of the docset ? Sure

**Comment by Kapeli** [comment]
Yes, the archive at the root doesn't work for some reason. The archive at `Kafka/versions/0.8.2/kafka.tgz` works.

**Comment by Igosuki** [comment]
The blob doesn't leave any differences, I'll just overwrite it with two commits to make sure.

**Pull request closed without merging**
