### PR TITLE
new ClojureScript docset

### PR DESCRIPTION
**Pull request by shaunlebron**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by shaunlebron** [comment]
@Kapeli, is there a process for getting this docset into the official set?

**Comment by Kapeli** [comment]
No, sorry. The "official set" is only for docsets made by me.

**Comment by shaunlebron** [comment]
Okay.  Just want to say it might be nice when searching "All Docsets" to show results for user-contributed, even if separated from the main ones.

**Comment by Kapeli** [comment]
That's planned, but I'm not sure when I'll get to it.

**Pull request merged**
