### PR TITLE
Add Kubernetes API docset

### PR DESCRIPTION
**Pull request by ruoshan**
there is an existing Kubernetes docset that's quite outdated. this
docset is a light one, with only API reference (up to date).

### CODE REVIEW

**Comment by Kapeli** [comment]
I don't think we should have 2 docsets for the same thing. Ideally the existing docset should be updated or replaced.

// cc @nextrevision

**Comment by ruoshan** [comment]
Yeah~ agree.

**Comment by nextrevision** [comment]
👍 will look into it today

**Comment by nextrevision** [comment]
I'm fine with replacing the existing kubernetes docset with this. Feel free to replace mine.

**Comment by Kapeli** [comment]
@ruoshan Please make a new pull request that replaces @nextrevision's docset with yours.

**Comment by ruoshan** [comment]
Okay, will do. Thanks you two.

**Pull request closed without merging**
