### PR TITLE
Kafka docset

### PR DESCRIPTION
**Pull request by Igosuki**
I created a trivial Kafka docset based on the official apache documentation

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation: can't unarchive the docsets.

Tar output is:
```
../../../kafka_docset/kafka.docset/: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/: Path contains '..'
../../../kafka_docset/kafka.docset/._icon.png.RU6h72: Path contains '..'
../../../kafka_docset/kafka.docset/icon.png: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Info.plist: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/._docSet.dsidx.vJdUDs: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/docSet.dsidx: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/Documents/: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/Documents/css: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/Documents/documentation.html: Path contains '..'
../../../kafka_docset/kafka.docset/Contents/Resources/Documents/styles.css: Path contains '..'
tar: copyfile unpack (../../../kafka_docset/kafka.docset/Contents/Resources/docSet.dsidx) failed: No such file or directory
tar: qtn_file_apply_to_path(../../../kafka_docset/kafka.docset/Contents/Resources/._docSet.dsidx): No such file or directory
tar: copyfile unpack (../../../kafka_docset/kafka.docset/icon.png) failed: No such file or directory
tar: qtn_file_apply_to_path(../../../kafka_docset/kafka.docset/._icon.png): No such file or directory
tar: Error exit delayed from previous errors.
```

**Comment by Igosuki** [comment]
Those files are in the repo ...
https://github.com/Igosuki/kafka_docset/blob/master/kafka.docset/Contents/Resources/docSet.dsidx
https://github.com/Igosuki/kafka_docset/blob/master/kafka.docset/Contents/Info.plist

What command are you using so that I can repeat and fix it ?

**Comment by Kapeli** [comment]
The issue is that the docset is not archived correctly. Running `/usr/bin/bsdtar -zxf` over the archive should give the same error.

The full command to verify everything can be found at https://github.com/Kapeli/Dash-User-Contributions/blob/master/.travis.yml#L6.

**Comment by Igosuki** [comment]
Thanks, I'll fix that no worries

**Pull request closed without merging**
