### PR TITLE
Update Packer docset to version 0.10.2

### PR DESCRIPTION
**Pull request by dserodio**

### CODE REVIEW

**Comment by dserodio** [comment]
This is my first PR to this repo, I hope I did everything right :)

**Comment by Kapeli** [comment]
You need to add the docset at this path as well: `Packer/Packer.tgz`, not just at `Packer/versions/0.10.2/Packer.tgz`.

@dazoakley Please check the docset if you can and let me know if anything is wrong.

**Comment by dazoakley** [comment]
Yup as @Kapeli says, it needs the .gz files.

I can't actually check the content until next week though I'm afraid - I'm between jobs and don't have a functioning laptop at the mo. :(

I'll be back online and able to do so next week. :)

**Comment by dserodio** [comment]
I amended the commit adding `Packer/Packer.tgz`

**Comment by dazoakley** [comment]
Looks ok to me - the only thing I have noticed that's missing is the index page when you click on the docset (in Dash).

**Comment by Kapeli** [comment]
Great. @dserodio if you can please fix the index page issue in a new pull request.

**Pull request merged**
