### PR TITLE
openFrameworks 0.11.1 update

### PR DESCRIPTION
**Pull request by icq4ever**
if any issue or mistake. let me know.
thank you.

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation. A lot of entries point to files that don't exist:

```
Checking openFrameworks/openFrameworks.tgz...
File not found at "of3d_primitives_8cpp.html.html" for entry with row id "189" of "openFrameworks.docset"
File not found at "of3d_primitives_8h.html.html" for entry with row id "190" of "openFrameworks.docset"
File not found at "of3d_utils_8cpp.html.html" for entry with row id "191" of "openFrameworks.docset"
File not found at "of3d_utils_8h.html.html" for entry with row id "192" of "openFrameworks.docset"
File not found at "of_camera_8cpp.html.html" for entry with row id "193" of "openFrameworks.docset"
File not found at "of_camera_8h.html.html" for entry with row id "194" of "openFrameworks.docset"
File not found at "of_easy_cam_8cpp.html.html" for entry with row id "195" of "openFrameworks.docset"
File not found at "of_easy_cam_8h.html.html" for entry with row id "196" of "openFrameworks.docset"
File not found at "of_mesh_8h.html.html" for entry with row id "197" of "openFrameworks.docset"
File not found at "of_mesh_8inl.html.html" for entry with row id "198" of "openFrameworks.docset"
File not found at "of_node_8cpp.html.html" for entry with row id "199" of "openFrameworks.docset"
File not found at "of_node_8h.html.html" for entry with row id "200" of "openFrameworks.docset"
File not found at "of_app_base_window_8h.html.html" for entry with row id "201" of "openFrameworks.docset"
File not found at "of_app_e_g_l_window_8cpp.html.html" for entry with row id "202" of "openFrameworks.docset"
File not found at "of_app_e_g_l_window_8h.html.html" for entry with row id "203" of "openFrameworks.docset"
File not found at "of_app_g_l_f_w_window_8cpp.html.html" for entry with row id "204" of "openFrameworks.docset"
File not found at "of_app_g_l_f_w_window_8h.html.html" for entry with row id "205" of "openFrameworks.docset"
File not found at "of_app_glut_window_8cpp.html.html" for entry with row id "206" of "openFrameworks.docset"
File not found at "of_app_glut_window_8h.html.html" for entry with row id "207" of "openFrameworks.docset"
File not found at "of_app_no_window_8cpp.html.html" for entry with row id "208" of "openFrameworks.docset"
...
```

**Comment by icq4ever** [comment]
hmm OK. how can I validate docset? I'll try again and check, then pull request.

**Comment by Kapeli** [comment]
To validate run this command at the base folder of the repo:

```
wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
```

**Comment by icq4ever** [comment]
thanks. I fixed. also checked as well.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
