### PR TITLE
Update Ramda docset to 0.15.1

### PR DESCRIPTION
**Pull request by smt**
[Separate PR](https://github.com/alexbepple/ramda-dash-docset/pull/4) is in for @alexbepple's docset repo.

### CODE REVIEW

**Comment by Kapeli** [comment]
@alexbepple is it ok to merge this?

**Comment by Kapeli** [comment]
I've checked the docset and everything looks fine, except for one thing: the index page doesn't work and Dash shows a file not found error when you click on the docset in the docset browser.

This is because the index.html in your docset seems to redirect to a page that doesn't exist.

**Comment by smt** [comment]
I looked at it this morning, and I think I need to defer to @alexbepple to make the necessary adjustments to his build scripts.

**Comment by Kapeli** [comment]
@smt If you want you can somewhat fix it yourself. The old index page is missing for some reason, but you can point the index page to the API reference instead. Edit the Info.plist and set `dashIndexFilePath` to `docs/index.html`.

**Comment by alexbepple** [comment]
PR #571

**Pull request closed without merging**
