### PR TITLE
Bumped Love2d to version 11.2

### PR DESCRIPTION
**Pull request by Cronos87**

### CODE REVIEW

**Comment by Kapeli** [comment]
Your `docset.json` contains version `11.0` 2 times, and no version `11.2`, for which you added the archive.

**Comment by Cronos87** [comment]
Indeed. I just fixed it. Sorry for this.

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by Cronos87** [comment]
Thank you to accept the pull request! 👍

**Pull request merged**
