### PR TITLE
Update astropy to v3.1

### PR DESCRIPTION
**Pull request by saimn**

### CODE REVIEW

**Comment by Kapeli** [comment]
There's an entry in `docSet.dsidx` which points to a file that does not exist (note: case sensitive):

```
File not found at "api/astropy.units.function.logarithmic.M_bol.html" for entry with row id "4106" of "Astropy.docset"
```

**Comment by saimn** [comment]
The file is there, and there is actually two files with the same name, modulo the case: `M_bol.html` and `m_bol.html`. Could this be the origin of the error ? 
Maybe a solution could be to remove one of the files from the archive ?

```
❯ less Astropy.tgz | grep -i logarithmic.m_bol
-rw-r--r-- simon/users     6463 2019-04-02 09:53 Astropy.docset/Contents/Resources/Documents/.doctrees/api/astropy.units.function.logarithmic.M_bol.doctree
-rw-r--r-- simon/users     6469 2019-04-02 09:53 Astropy.docset/Contents/Resources/Documents/.doctrees/api/astropy.units.function.logarithmic.m_bol.doctree
-rw-r--r-- simon/users       88 2019-04-02 09:52 Astropy.docset/Contents/Resources/Documents/_sources/api/astropy.units.function.logarithmic.m_bol.rst.txt
-rw-r--r-- simon/users       88 2019-04-02 09:52 Astropy.docset/Contents/Resources/Documents/_sources/api/astropy.units.function.logarithmic.M_bol.rst.txt
-rw-r--r-- simon/users     4407 2019-04-02 10:18 Astropy.docset/Contents/Resources/Documents/api/astropy.units.function.logarithmic.M_bol.html
-rw-r--r-- simon/users     4432 2019-04-02 10:18 Astropy.docset/Contents/Resources/Documents/api/astropy.units.function.logarithmic.m_bol.html
```

**Comment by Kapeli** [comment]
That's definitely the issue, as the archive is extracted on a case-insensitive system sometimes and one of the files gets lost.

One of the files needs to be renamed to something else.

**Comment by Kapeli** [comment]
Still fails:

```
File not found at "api/astropy.units.function.logarithmic.m_bol.html" for entry with row id "4108" of "Astropy.docset"
```

You need to change the entry in docSet.dsidx too.

**Comment by saimn** [comment]
@Kapeli - thanks, this time it looks good.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
