### PR TITLE
add pwntools docset and improve IntelASMx86

### PR DESCRIPTION
**Pull request by Kira-cxy**

### CODE REVIEW

**Comment by Kapeli** [comment]
Please don't rename the folder of the docset you're updating/improving (leave it as `IntelASMx86`). Dash uses the folder name as the unique identifier, so changing it makes Dash treat the docset as a completely new one.

**Comment by Kira-cxy** [comment]
I thought the origin name cannot describe the docset precisely, so I did the change. Wish to rename it.

**Comment by Kapeli** [comment]
The folder name isn't displayed to users at all, it's just used internally by Dash as an identifier. You should rename the name in `docset.json` instead if you want.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
