### PR TITLE
Update from version 0.17.1 to 0.18.0

### PR DESCRIPTION
**Pull request by serhanaya**
[Fixed] Added Scikit-learn.tgz

Update to the new version of scikit-learn (v.0.18).

P.S Line 25 of the file scikit-to-dash.py needs to be changed from
urllib.urlretrieve to urllib.request.urlretrieve (I am waiting for my
pull request to be accepted by Aziz Alto).

### CODE REVIEW

**Comment by serhanaya** [comment]
I use Dash a lot, I wanted to contribute by updating scikit-learn docset, which recently updated to v.0.18. Although, the docset worked on my computer, I see that there is check error. Unfortunately, I don’t know how to resolve this.

**Comment by jaypeedevlin** [comment]
Hey @serhanaya, [I just did the same thing you did](https://github.com/Kapeli/Dash-User-Contributions/pull/1116)! 😂

I actually redid the folder etc with a better icon, and updated `Scikit` to `scikit-learn` because I'm a bit pedantic about capitalization and getting the names right etc.  Yours is in first so I'm happy for mine to be closed.

**Comment by jaypeedevlin** [comment]
Also FWIW, the test failure seems to do with the online fallback, as far as I can see.

**Comment by serhanaya** [comment]
#1116 is the proper update to scikit-learn docs (to v.18.0), so this can be closed.

**Pull request closed without merging**
