### PR TITLE
openFrameworks docset update - re-fork, PR again

### PR DESCRIPTION
**Pull request by icq4ever**
sorry for broken forked.
still I don't understand what is the default git pull rebase option. 
I think fork syncing should be done by github website..

- docset updated
- docset main version updated
- docset tgz file name fixed (case-sensitive)

### CODE REVIEW

**Comment by icq4ever** [comment]
okay... this looks not good. I'll update soon.

**Comment by icq4ever** [comment]
interesting. this not happen on linux builded docset. I'll try tomorrow on linux machine. until then, close this PR.

**Comment by icq4ever** [comment]
sofar no error on test, hope this works

**Comment by icq4ever** [comment]
@Kapeli just update docset using docsetutils on mac. I guess no error.

**Comment by Kapeli** [comment]
Thank you!

**Pull request merged**
