### PR TITLE
added logstash docs

### PR DESCRIPTION
**Pull request by WoLpH**
See #451

### CODE REVIEW

**Comment by Kapeli** [comment]
Looks good.

One issue: you have a `specific_versions` entry for version `1.5.0.RC2`, but the docset archive for it doesn't exist. Either remove the entry from the `docset.json`, or add the docset archive.

**Comment by WoLpH** [comment]
Ok, I've rebased it in.

PS: Generally squashing commits is far easier to do when merging in changes than on the source repo. At the source repo it's useful to have those commits. Usually not at the destination.

To easily squash them while merging:
```
git remote add wolph git@github.com:Kapeli/Dash-User-Contributions.git
git fetch wolph
git merge --squash wolph/master
```

**Comment by Kapeli** [comment]
Great. Thanks for the contribution and the tip, I didn't know you could squash while merging.

**Comment by WoLpH** [comment]
I've actually just requested it as a Github feature as well, would be useful to have a checkbox to squash while merging in pull requests :)

**Pull request merged**
