### PR TITLE
Skeleton 1.0.0

### PR DESCRIPTION
**Pull request by ksmarty**

### CODE REVIEW

**Comment by ksmarty** [comment]
@Kapeli not sure why its not passing. Any ideas?

**Comment by Kapeli** [comment]
The docSet.dsdix of the docset contains entries with new line characters in the name, which is not supported.

**Comment by ksmarty** [comment]
I believe I have fixed the docSet.dsdix to follow guidelines

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
