### PR TITLE
Add NixPkgs_Stable docset (22.05/docver=1.0.0)

### PR DESCRIPTION
**Pull request by aiotter**
Fresh new docset for [NixPkgs](https://nixos.org/manual/nixpkgs/stable/index.html)!

### CODE REVIEW

**Comment by aiotter** [comment]
They do not provide icon with 32x32 size

**Comment by Kapeli** [comment]
> They do not provide icon with 32x32 size

In this case you need to remove the 16x16 icon ☹️

**Comment by aiotter** [comment]
Hmm, making it icon-less seems bad. I'll try to get the icon from another source.

**Comment by Kapeli** [comment]
Please open a new pull request when ready.

**Comment by aiotter** [comment]
Okay, thanks for letting me know! I wasn't available for a while. I'll create a new one soon.

**Pull request closed without merging**
