### PR TITLE
Update RFCs docset

### PR DESCRIPTION
**Pull request by FiloSottile**
You can download the archive at
https://dl.bintray.com/filosottile/generic/RFCs.docset-v1.6.0.tgz

/cc @willnorris, @weppos

### CODE REVIEW

**Comment by Kapeli** [comment]
`icon.png` needs to be 16x16 in size. You also need to add `icon@2x.png` which needs to be 32x32 in size.

**Comment by weppos** [comment]
Ciao @FiloSottile, thanks! Let's get https://github.com/willnorris/rfcdash/pull/9 sorted out and then I will help with this PR.

**Comment by weppos** [comment]
@Kapeli out of curiosity, can we skip the icon as it has been so far? There is really no special applicable icon here.

See https://github.com/Kapeli/Dash-User-Contributions/pull/1817. In the past I intentionally left it with no icon, and the default one was used.

Would you be ok with that?

**Comment by Kapeli** [comment]
@weppos sure, icons are not required, but if they're added they need to meet the requirements.

**Comment by weppos** [comment]
@FiloSottile I don't think I can edit your PR. Do you mind to remove the change to the icon?

**Comment by Kapeli** [comment]
I can merge and remove the icon. Is that ok @FiloSottile?

**Comment by FiloSottile** [comment]
Deleted the icon, sorry for the radio silence!

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
