### PR TITLE
Add TensorFlow 1.3

### PR DESCRIPTION
**Pull request by ppwwyyxx**

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation. A lot of entries in the docSet.dsidx point to files that don't exist. See https://travis-ci.org/Kapeli/Dash-User-Contributions/builds/265318267 for the log.

**Comment by ppwwyyxx** [comment]
The first error in the log shows this file doesn't exist, but it does. What's going on? 
```
╰─$wget https://github.com/ppwwyyxx/Dash-User-Contributions/raw/ddd9070cfd68804b9644fdcd7bc64c17685b16b3/docsets/TensorFlow/TensorFlow.tgz
╰─$tar xzf TensorFlow.tgz
╰─$find | grep versions/master/api_docs/python/tf/Summary/Audio.html
./TensorFlow.docset/Contents/Resources/Documents/versions/master/api_docs/python/tf/Summary/Audio.html
```

**Comment by Kapeli** [comment]
Your archive contains both "versions/master/api_docs/python/tf/Summary/Audio.html" and "versions/master/api_docs/python/tf/summary/audio.html". Most Macs are case-insensitive, so you shouldn't have that.

**Comment by ppwwyyxx** [comment]
Ah I see. Thanks!
These are indeed two different pages:
https://www.tensorflow.org/versions/master/api_docs/python/tf/Summary/Audio
https://www.tensorflow.org/versions/master/api_docs/python/tf/summary/audio

I'll see how I can work around it..

**Pull request closed without merging**
