### PR TITLE
Update React Native v0.4.0

### PR DESCRIPTION
**Pull request by epitaphmike**

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by epitaphmike** [comment]
How long does it typically take for a merge to go into a new Dash build?

**Comment by Kapeli** [comment]
It depends. As soon as I merge, I run a command which takes the docset and uploads it to my servers. Normally this takes 5 minutes max. I'm in rural France now with really bad Internet, so I have no idea how long it will take. Sorry!

**Comment by epitaphmike** [comment]
No worries at all. Thank you.

**Comment by Kapeli** [comment]
Should be live now.

**Comment by epitaphmike** [comment]
It is. Thanks again.

**Pull request merged**
