### PR TITLE
add openvswitch 2.11.90 docset

### PR DESCRIPTION
**Pull request by halfcrazy**
Note: 
I have not found an appropriate icon. :sad

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:
```
Could not find Info.plist at "/Users/bogdan/Downloads/Dash-User-Contributions-feat-openvswitch/docsets/Openvswitch/versions/2.11.90/unarchive_temp/Openvswitch.docset/Contents/Info.plist"
```

Please note that the `Info.plist` name is case-sensitive.

**Comment by halfcrazy** [comment]
copy, I'll check

**Comment by halfcrazy** [comment]
Update

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
