### PR TITLE
Update RFCs docset

### PR DESCRIPTION
**Pull request by pointlessone**
The docset file: [RFCs.tgz](https://files.pointless.one/RFCs-docset/2024.09.19-1.0.0/RFCs.tgz).

### CODE REVIEW

**Comment by Kapeli** [comment]
The link points to a file that does not exist (error 404).

**Comment by pointlessone** [comment]
Sorry, fixed.

**Comment by Kapeli** [comment]
The docset should be directly inside the archive (i.e. don't archive any enclosing folder). In your archive the docset is inside a `dist` folder. 

I've remade the archive. If you can, please make sure to archive the docset directly on your next submission. 

Sorry for the inconvenience!

**Comment by pointlessone** [comment]
Thank you. Absolutely.

**Comment by weppos** [comment]
@Kapeli @pointlessone I used to be the maintainer of the RFC docset (see https://github.com/Kapeli/Dash-User-Contributions/pull/2480), that was originally created by @willnorris

[The repo](https://github.com/willnorris/rfcdash) was not updated for a few years as the RFCs were migrated. Last month [all the issues were cleared](https://github.com/willnorris/rfcdash/pull/11), and I started the process to get the docset ready for publishing.

However, as I came here today, I noticed that last week the repo was replaced with a new one.

How do you want to move forward in addressing the conflict? Any preference?

**Comment by Kapeli** [comment]
@weppos Can you point me to a downloadable docset with @Tenzer's changes? My preference would be towards users getting the version of the docset with the least issues, so I'd start by comparing the 2 docsets. As I'm not familiar with this docset, any help / suggestions are greatly appreciated.

**Comment by weppos** [comment]
Sure thing. Please give me until next week, this one I have limited connectivity.

**Comment by weppos** [comment]
@Kapeli I uploaded the file, you can find it at https://storage.googleapis.com/rfcdash/RFCs.docset-v2.0.0.tgz

Also referenced in https://github.com/willnorris/rfcdash/blob/master/RFCs.xml

**Comment by weppos** [comment]
Hi @Kapeli, did you have the chance to take a look? Anything I can help with?

**Comment by pointlessone** [comment]
My code is in Ruby so it's not exactly compatible with @weppos script. I'm fine if it's being used as reference (it's under Apache license) if @weppos is willing to maintain it and update the docset once in a while.

**Pull request merged**
