### PR TITLE
Adjust kotlin docs to add ToC and Test docs

### PR DESCRIPTION
**Pull request by snowe2010**
- add Table of Contents to every page
- add kotlin.test docs
- make CSS adjustments automatic
- some general code cleanup
- update to 1.9.20

### CODE REVIEW

**Comment by snowe2010** [comment]
This is just forked from a repo that is already used here. Does the `Info.plist` have to be specified in some way? 
image

**Comment by snowe2010** [comment]
Looks like it's case sensitive. I'm not sure how the previous repos have had this work lol.

**Comment by Kapeli** [comment]
Thank you!

**Comment by Kapeli** [comment]
> Looks like it's case sensitive. I'm not sure how the previous repos have had this work lol.

🤷 The previous pull request for this docset had the correct casing for Info.plist: https://github.com/Xm798/Dash-User-Contributions/blob/2ce2d009c40117e2c8eeb3baaf9b588c31435c96/docsets/Kotlin/kotlin.tgz

**Pull request merged**
