### PR TITLE
Update TailwindCSS to 1.1(.3)

### PR DESCRIPTION
**Pull request by godbout**
hopefully all is good here! thanks.

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by godbout** [comment]
hey sorry, something seem to have not worked correctly. the docset downloaded seems to be an old one (if there's no cache issue with dash?). hence i'm gonna have to do another PR.

**Comment by Kapeli** [comment]
The release notes page for the docset you submitted (https://github.com/godbout/Dash-User-Contributions/blob/165dc721553619132410be427ca2dac37651f785/docsets/Tailwind_CSS/tailwindcss.tgz) mention v1.0.

It might be an issue on my end as well, but please check if the docset you submitted is for v1.1.

**Comment by godbout** [comment]
Hmm. There might be something that I’ve forgot then. I’ll check the docs again and see if I need to make a new update later today. Thank you!

**Comment by godbout** [comment]
@Kapeli sorry, i checked and i don't get it. do you mean a version number within the package itself (.docset; .tgz)? i don't remember anything like this. the `docset.json` itself seems correct. i've used the same process for my latest PR, and that one worked fine.

**Comment by godbout** [comment]
ok, i think it was my issue. my `.docset` was correct, but i forgot to archive it to the `.tgz` correctly. thanks!

**Pull request merged**
