### PR TITLE
Update PyTorch to v1.0.0

### PR DESCRIPTION
**Pull request by JiamingSuen**
No obvious visual flaws with the new pytorch sphinx theme.

### CODE REVIEW

**Comment by Kapeli** [comment]
You need to update the [main version](https://github.com/Kapeli/Dash-User-Contributions/blob/f73570a3d8439117b0a9c00a867244578082e550/docsets/PyTorch/docset.json#L3-L4) as well, not just the specific one.

**Comment by JiamingSuen** [comment]
Sure, my mistake

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by neilsustc** [comment]
Awesome

**Comment by hologerry** [comment]
Could please update the docset icon to the newer version ?

**Pull request merged**
