### PR TITLE
Add Packer 0.12.0 docset

### PR DESCRIPTION
**Pull request by okuramasafumi**

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:
```
File not found at "docs/extend/command.html" for entry with row id "80" of "Packer.docset"
```

This means that you have an entry that points to a path that doesn't exist.

**Comment by okuramasafumi** [comment]
@Kapeli I fixed the issue. Please check it out!

**Comment by Kapeli** [comment]
Thank you! 👍 

@dazoakley This looks good to me so I'll merge it. If anything is wrong, let me know and I'll revert it.

**Comment by dazoakley** [comment]
Looks good to me 👍

**Pull request merged**
