### PR TITLE
Adds NodeMongoDB docset

### PR DESCRIPTION
**Pull request by fcoury**
Docset for https://github.com/mongodb/node-mongodb-native

### CODE REVIEW

**Comment by Kapeli** [comment]
You need to add your docset folder under the `docsets` folder.

There's no need to end your folder name with `_Docset`.

Your docset isn't archived correctly (it contains several folders). See archive instructions at https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset.

**Comment by fcoury** [comment]
Working on the feedback @Kapeli thanks!

**Comment by fcoury** [comment]
Done @Kapeli be welcome to take another pass.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
