### PR TITLE
Added ns-3 docset.

### PR DESCRIPTION
**Pull request by tnull**
I added a docset for the [ns-3](https://www.nsnam.org/) network simulator. 
However, the `ns-3.tgz` is around 2.5 GB, so I'd need somewhere to upload it before the PR can be accepted.

Regards!

### CODE REVIEW

**Comment by tnull** [comment]
I uploaded the `ns-3.tgz`, you can pull it from: https://tnull.de/static/ns-3.tgz

**Comment by Kapeli** [comment]
2.5 GB is a bit too large unfortunately. Any idea what's causing the size? The docset has around 2400 classes, so it shouldn't be quite that large.

**Comment by tnull** [comment]
I think the size comes mostly from huge number of `png` files. These should be inheritance graphs and collaboration diagrams generated by `doxygen`/`dot`. Should I exclude them? Then, however, the documentary might be broken at some points (as in you would see that there is something missing).

**Comment by Kapeli** [comment]
Maybe configure Doxygen so it doesn't generate graphs at all?

**Comment by tnull** [comment]
Yep, I disabled what I could find and was able to push the file size of `ns-3.tgz` to 72 megabytes. See the  updated commits! :)

**Comment by Kapeli** [comment]
Great. Please fix these issues though:
```
Not 16x16: "icon.png" in "ns-3"
Not 32x32: "icon@2x.png" in "ns-3"
```

**Comment by tnull** [comment]
Done. Strange, each of the icons were exactly twice as large. Must have done sth. wrong while saving them.

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
