### PR TITLE
add dark mode for some of TailwindCSS color palettes and tables

### PR DESCRIPTION
**Pull request by godbout**
currently for palettes and tables. rest will come later (some issues with inputs).

### CODE REVIEW

**Comment by godbout** [comment]
something changed in the ci between now and May 28? i have fake folder in a path just to be able to go up one level. hasn't changed since May 28 and the build passed at the time. just out of curiosity. i can find another way to handle that.

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by Kapeli** [comment]
> something changed in the ci between now and May 28? i have fake folder in a path just to be able to go up one level. hasn't changed since May 28 and the build passed at the time. just out of curiosity. i can find another way to handle that.

The last change to the CI was on 04.09.2019.

**Comment by godbout** [comment]
fair enough. thanks.

**Pull request merged**
