### PR TITLE
Add new docset for ClickHouse v21.9.4.35

### PR DESCRIPTION
**Pull request by ruoshan**

### CODE REVIEW

**Comment by ruoshan** [comment]
@Kapeli no CI running now?

**Comment by Kapeli** [comment]
No CI anymore. I run it manually using this command:

```
git clone https://github.com/Kapeli/Dash-User-Contributions.git 3485 && cd 3485 && git pull https://github.com/Kapeli/Dash-User-Contributions refs/pull/3485/head && wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
```

Everything seems ok. Should I merge?

**Comment by ruoshan** [comment]
> No CI anymore. I run it manually using this command:
> 
> 
> 
> ```
> 
> git clone https://github.com/Kapeli/Dash-User-Contributions.git 3485 && cd 3485 && git pull https://github.com/Kapeli/Dash-User-Contributions refs/pull/3485/head && wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
> 
> ```
> 
> 
> 
> Everything seems ok. Should I merge?

yea, go ahead

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
