### PR TITLE
Update Electron to v1.4.3

### PR DESCRIPTION
**Pull request by sidneys**

### CODE REVIEW

**Comment by Kapeli** [comment]
@sidneys: You also need to add the tgz to `docsets/electron/electron.tgz`.

@pirafrank: If you notice anything wrong, let me know.

**Comment by pirafrank** [comment]
Hi,
I'll check that tomorrow.
Btw I've docset set up and ready for commit. I've just forgot to do that. I could commit afterwards for versions previous 1.4.3 if it's ok for you. 

Francesco Pira

**Comment by Kapeli** [comment]
@pirafrank Please make a pull request with your update for this docset. I much prefer docsets being updated by only one author.

@sidneys If your version of the docset has any improvements, please let me and @pirafrank know.

**Comment by pirafrank** [comment]
Ok, docset for 1.4.3 was already packed. 
I'll do once @ home. About 3h. 

@sidneys I'll leave you among contributors if it's ok for you.

Francesco Pira

**Pull request closed without merging**
