### PR TITLE
Add igraph docset

### PR DESCRIPTION
**Pull request by szhorvat**
This PR adds a docset for [the igraph C library](https://igraph.org/c/). See https://igraph.org/

This was prepared with the trial version of Dash. Per the readme of this repo, I would like to request a Dash license to make future maintenance easier. My email address is szhorvat at gmail. We are two members of the igraph core team who use macOS and who worked on the docset generator. If possible to receive a license for both, that would be useful and appreciated.

At a later stage I plan to contribute docsets for the Python, R and perhaps Mathematica interfaces of igraph as well.

### CODE REVIEW

**Comment by szhorvat** [comment]
And a question about docsets:

Is there a way to control the word displayed to the left of search results?

image

These seem to reflect the name of the HTML file now.

Also, why do some result lack this word?

**Comment by szhorvat** [comment]
igraph 0.9.3 was just released; updated docset in 2nd commit.

**Comment by szhorvat** [comment]
Yet another question: How do I break the table of contents into meaningful parts as in the screenshot here? --> https://kapeli.com/dash_guide#tableOfContents

**Comment by Kapeli** [comment]
Failed validation:

```
Found regular icon, but missing retina icon in "igraph"
Not 16x16: "icon.png" in "igraph"
```

You need `icon.png` which should be exactly `16x16` and `icon@2x.png` which should be exactly `32x32`.

**Comment by Kapeli** [comment]
> Is there a way to control the word displayed to the left of search results?

Yes. To do this you need to add this anywhere in the `path` in `docSet.dsidx` entries: `<dash_entry_titleDescription=percent_encoded_value>`

Entries don't show a description when the description was determined to be the same as the entry name.

**Comment by Kapeli** [comment]
> Yet another question: How do I break the table of contents into meaningful parts as in the screenshot here? --> https://kapeli.com/dash_guide#tableOfContents

This is possible by adding the ToC sections too.

Do this:
1. Set the DashDocSetFamily key to `dashtoc2`
2. Add anchors like this:

```
<a class="dashAnchor" name="//dash_ref/type/name/isSection (1 or 0)"></a>
```

So, you'd have this when you want to start a section with instance methods:

```
<a class="dashAnchor" name="//dash_ref/Method/Instance Methods/1"></a>
```

And then to add methods:

```
<a class="dashAnchor" name="//dash_ref/Method/some method/0"></a>
```

Unfortunately this requires that the instance methods and class methods to be grouped in the docs as well (i.e. in the order they appear in the page). If this is not the case for the docs you're indexing, let me know and I'll provide instructions on how to get around that too.

**Comment by szhorvat** [comment]
Thanks for the comments!



> You need `icon.png` which should be exactly `16x16` and `icon@2x.png` which should be exactly `32x32`.

This is fixed now. Originally I used a single icon as I got the impression from [here](https://kapeli.com/docsets#addingicon) that this would be sufficient.

> Yes. To do this you need to add this anywhere in the `path` in `docSet.dsidx` entries: `<dash_entry_titleDescription=percent_encoded_value>`

Descriptions are added as well.

As for the ToC improvements, I will attempt it at a later time. From my side, the PR is good to go.

**Comment by Kapeli** [comment]
Great job. Thank you! 👍

**Comment by szhorvat** [comment]
@Kapeli Thanks for merging! I am wondering if we qualify for the offer of a free license, mentioned in the readme.

**Comment by Kapeli** [comment]
> @Kapeli Thanks for merging! I am wondering if we qualify for the offer of a free license, mentioned in the readme.

Sure! I've sent you a 2-user license to your email.

**Pull request merged**
