### PR TITLE
updates Nim docset for version 1.0.6

### PR DESCRIPTION
**Pull request by schmidh**

### CODE REVIEW

**Comment by Kapeli** [comment]
What's the purpose of the `tags` file?

**Comment by schmidh** [comment]
None. Must have slipped through somehow. It's automatically generated in Vim. I'll sort it out.

**Comment by schmidh** [comment]
Once you merge it, I will post a new docset version whenever a new version of Nim comes out. Normally this is about every two months. Docset and PR generation are fully automated now.

**Comment by schmidh** [comment]
Is this mergeable now as it stands or should I create a new PR?

**Comment by schmidh** [comment]
Sorry, I had to create new icon images. Will generate a new PR.

**Pull request closed without merging**
