### PR TITLE
Update XCTest Documentation

### PR DESCRIPTION
**Pull request by jk2K**

### CODE REVIEW

**Comment by Kapeli** [comment]
This docset doesn't have a `DocSetPlatformFamily` set in Info.plist. It's not a requirement to have it, but it's a regression from the old docset.

@joemasilotti are you ok with me merging this?

**Comment by joemasilotti** [comment]
@jk2K when did you generate the docset? For Xcode 7.2 or 7.3 beta?

**Comment by jk2K** [comment]
@joemasilotti  today, 2016-01-26， For Xcode 7.2

**Comment by joemasilotti** [comment]
Awesome, merge away!

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by jk2K** [comment]
My pleasure 😄

**Pull request merged**
