### PR TITLE
io.js docset

### PR DESCRIPTION
**Pull request by fundon**

### CODE REVIEW

**Comment by fundon** [comment]
Why the travis CI build failed?

**Comment by Kapeli** [comment]
```
Not 16x16: "icon.png" in "io.js"
Not 32x32: "icon@2x.png" in "io.js"
Checking io.js/io.js.tgz...
Could not find docset after unarchiving "/Users/travis/build/Kapeli/Dash-User-Contributions/docsets/io.js/io.js.tgz"
```

So, the icons are not 16x16 and 32x32 and the `io.js.tgz` does not directly contains a docset in it. You're not supposed to archive the folder that contains the docset. You should archive the docset itself.

**Comment by fundon** [comment]
Thanks,
Ok, i rebuild it.

**Comment by Kapeli** [comment]
Still fails. The reason is: https://github.com/Kapeli/Dash-User-Contributions/pull/307#issuecomment-71675625.

**Comment by fundon** [comment]
If everything is ok, I re-open a PR.

**Pull request closed without merging**
