### PR TITLE
feat: swift 5.7 update

### PR DESCRIPTION
**Pull request by roeybiran**

### CODE REVIEW

**Comment by Kapeli** [comment]
Please remove the `Sample_Docset.tgz`s from the pull request.

**Comment by roeybiran** [comment]
Done!

**Comment by Kapeli** [comment]
Please remove `docsets/Swift/versions/1.0.0/Sample_Docset.tgz` and `docsets/Swift/versions/1.0.1/Sample_Docset.tgz`

**Comment by Kapeli** [comment]
Thank you! ❤️

**Pull request merged**
