### PR TITLE
NativeScript 1.7.1 docset

### PR DESCRIPTION
**Pull request by alg**
Hi there,

Please accept my NativeScript docset. I ran it by the members of community on the official Slack channel and got some very nice feedback. So decided to share officially as opposed to passing through Dropbox.

Cheers.

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by alg** [comment]
Thanks for merging! How soon do they usually appear in the app?

**Comment by Kapeli** [comment]
5mins or so. You can't find it in Preferences > Downloads > User Contributed?

**Comment by alg** [comment]
Oh, I do now. Checked right after the merge and didn't see. Decided to ask. Thanks mate!

**Pull request merged**
