### PR TITLE
MNE

### PR DESCRIPTION
**Pull request by NeuroForLunch**
The docsets were too big for github so I uploaded & included the download links for them instead.

### CODE REVIEW

**Comment by Kapeli** [comment]
Are all these versions needed or could you skip some of them? As these docsets are rather large, I'd like to keep disk usage to a minimum.

**Comment by Kapeli** [comment]
Also, the floating banner/navigation at the top of pages goes over the anchors. Can you make the banner/navigation static instead of floating?

**Comment by NeuroForLunch** [comment]
Which versions should I keep?

**Comment by Kapeli** [comment]
I'd say just the latest one? Do a lot of people use the older versions?

**Comment by NeuroForLunch** [comment]
I was thinking the last one too

**Pull request merged**
