### PR TITLE
Submit again

### PR DESCRIPTION
**Pull request by TongG**
How about now?

### CODE REVIEW

**Comment by Kapeli** [comment]
All good. However, are you aware you could make this a Cocoa Pod and then it would show up on CocoaDocs.org? Then it would appear in Dash in Preferences > Downloads > Cocoa Docsets too.

**Comment by TongG** [comment]
Thank you for your tip, I will make this framework Cocoa Pod when the next version be released. That's OK this time. 😃

**Comment by Kapeli** [comment]
If you'll make it a Cocoa Pod, then there's no point in accepting this as I don't want the same docset to appear in two places. Sorry.

**Comment by TongG** [comment]
Fine, I'll resubmit pull request after completing it. Thank you.

**Comment by Kapeli** [comment]
You don't have to resubmit anything here. Just add Cocoa Pod support and it should automatically show up on Cocoa Docs.

**Comment by TongG** [comment]
Yep!

**Pull request closed without merging**
