### PR TITLE
Added Symfony Docs https://symfony.com/doc

### PR DESCRIPTION
**Pull request by pouyana**
Adds Symfony documentation guides from https://symfony.com/doc for all supported Symfony versions.

### CODE REVIEW

**Comment by Kapeli** [comment]
The docSet.dsdix contains an entry that points to "https://github.com/bitprophet/alabaster". Is this intentional?

Also you added an archive for `versions/5.0/Symfony_Docs.tgz`, but didn't add any `specific_version` that links to it.

**Comment by pouyana** [comment]
Hi indeed it shouldn't be added. The link was inside the index file, I should make the parser ignore the link and don't add it to the sqlite database. I will try to correct it.

About the version: 5.0 is the most recent version, should the most recent version be added to the versions folder or the file in root dir is enough?

I also saw there is an official Symfony API docset, is there a possibility to add these guides to that so all documentation are in one place?

**Comment by Kapeli** [comment]
> About the version: 5.0 is the most recent version, should the most recent version be added to the versions folder or the file in root dir is enough?

If you add the archive to the versions folder, you also need to mention it in `specific_versions` in the docset.json. Otherwise, you only need the latest version in the root dir. Either way is fine, it's up to you.


> I also saw there is an official Symfony API docset, is there a possibility to add these guides to that so all documentation are in one place?

I haven't seen any demand for this yet (no user requested the guides). I'll watch how popular your docset becomes and I'll consider including it into the main Symfony docset based on that.

**Comment by pouyana** [comment]
So I think this should work, thanks for waiting :).

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
