### PR TITLE
ffmpeg and Libav API documents 

### PR DESCRIPTION
**Pull request by steve3d**
Sorry for the tittle
The ffmpeg and libav API document

### CODE REVIEW

**Comment by steve3d** [comment]
Ok. Failed again, But the missing files exists, I've double checked.  Don't know why checks failed.

**Comment by steve3d** [comment]
All those missing files also exists in my previous PR.

**Comment by Kapeli** [comment]
The paths are case sensitive.

For example in the index you have:
```
api/structNuvContext.html
```

While the actual file is at:
```
api/structNUVContext.html
```

Also, `Libav/Libav.tgz` should be an actual tgz, not a symlink to the one found in versions.

**Comment by steve3d** [comment]
OK, got it, linux filesystem is case sensitive. and Libav/Libav.tgz should be the newest version of docset right?

**Comment by Kapeli** [comment]
Yes.

**Comment by steve3d** [comment]
OK then, seems building the docset under mac is not a good idea, I'll try to build it under linux, which has case sensitive fs.

**Comment by steve3d** [comment]
@Kapeli, I finally found the problem, those missing files are caused by typo in source files.

Now I have two solution, 
- filter those typo symbols in source file to make it point to correct files. But most of these symbols are not exposed by the library, so it's only value is just a reference. but these might change over different versions.
- skip build all source files, so the docset only includes exported api from the library.

which should I do?

**Comment by Kapeli** [comment]
When you're adding the index entry, can you convert the path to the case-sensitive one?

**Comment by steve3d** [comment]
like these two
```api/structNuvContext.html
api/structNUVContext.html```
the real symbol is NuvContext, under mac, the first generated file will survive, but under linux, I got both file exists: they both exists.

**Comment by steve3d** [comment]
@Kapeli , I've made some research, build a typo symbol list to skip is not possible, so look at the error log of my first PR, for example , the RiceContext and RICEContext, ffmpeg and libav both use them.

So the only way to do this is building these docsets on a case-sensitive filesystem. Or build these docsets without doxygen source files. for example I can create two version of docset for ffmpeg 3.1.4, one include all documents, another only includes the documents for header files.

Which one is better?

**Comment by Kapeli** [comment]
I don't know, sorry.

**Pull request closed without merging**
