### PR TITLE
add Tailwind CSS 3.0.0

### PR DESCRIPTION
**Pull request by godbout**

### CODE REVIEW

**Comment by godbout** [comment]
ran the docsetcontrib exec, seems all good 👍️

**Comment by Kapeli** [comment]
Please delete the `unarchive_temp` from the pull request.

**Comment by godbout** [comment]
well that'll teach me to do stuff in a rush.
hopefully good now.

**Comment by Kapeli** [comment]
Merged in https://github.com/Kapeli/Dash-User-Contributions/pull/3522

**Pull request closed without merging**
