### PR TITLE
Docset for DokuWiki release Detritus

### PR DESCRIPTION
**Pull request by gamma**

### CODE REVIEW

**Comment by gamma** [comment]
I do not understand why the PR fails. Is it because auf the missing version information in the top level of the json file? I thought either the versions definition or the specific versions would be enough.

**Comment by Kapeli** [comment]
> I thought either the versions definition or the specific versions would be enough.

You need to have the main version too, just having specific versions is not enough. Specific versions are only for the docsets inside the popover (to install specific versions). You still need to have the main docset which gets updated and so on.

**Comment by gamma** [comment]
Is it OK to have the current version link one of the specific versions?

**Comment by Kapeli** [comment]
I think it works but I've never tried it. It would be best if it would link to its own archive.

**Comment by Kapeli** [comment]
Issues:

```
File not found at "_variables/ACT.html" for entry with row id "4581" of "DokuWiki.docset"
File not found at "_variables/AUTH.html" for entry with row id "4582" of "DokuWiki.docset"
File not found at "_variables/B.html" for entry with row id "4584" of "DokuWiki.docset"
File not found at "_variables/BL.html" for entry with row id "4585" of "DokuWiki.docset"
File not found at "_variables/CACHE.html" for entry with row id "4587" of "DokuWiki.docset"
File not found at "_variables/COLOR.html" for entry with row id "4589" of "DokuWiki.docset"
File not found at "_variables/DATE.html" for entry with row id "4594" of "DokuWiki.docset"
File not found at "_variables/DATE_AT.html" for entry with row id "4595" of "DokuWiki.docset"
File not found at "_variables/DEL.html" for entry with row id "4596" of "DokuWiki.docset"
File not found at "_variables/DL.html" for entry with row id "4598" of "DokuWiki.docset"
File not found at "_variables/DST.html" for entry with row id "4599" of "DokuWiki.docset"
File not found at "_variables/ERROR.html" for entry with row id "4600" of "DokuWiki.docset"
File not found at "_variables/EXT.html" for entry with row id "4605" of "DokuWiki.docset"
File not found at "_variables/FILE.html" for entry with row id "4607" of "DokuWiki.docset"
File not found at "_variables/H.html" for entry with row id "4610" of "DokuWiki.docset"
File not found at "_variables/HEIGHT.html" for entry with row id "4611" of "DokuWiki.docset"
File not found at "_variables/ID.html" for entry with row id "4613" of "DokuWiki.docset"
File not found at "_variables/IDX.html" for entry with row id "4614" of "DokuWiki.docset"
File not found at "_variables/IMG.html" for entry with row id "4615" of "DokuWiki.docset"
File not found at "_variables/IN.html" for entry with row id "4616" of "DokuWiki.docset"
File not found at "_variables/INFO.html" for entry with row id "4617" of "DokuWiki.docset"
File not found at "_variables/INPUT.html" for entry with row id "4618" of "DokuWiki.docset"
File not found at "_variables/Indexer.html" for entry with row id "4623" of "DokuWiki.docset"
File not found at "_variables/L.html" for entry with row id "4626" of "DokuWiki.docset"
File not found at "_variables/MEDIA.html" for entry with row id "4631" of "DokuWiki.docset"
File not found at "_variables/MIME.html" for entry with row id "4632" of "DokuWiki.docset"
File not found at "_variables/MSG.html" for entry with row id "4633" of "DokuWiki.docset"
File not found at "_variables/NS.html" for entry with row id "4635" of "DokuWiki.docset"
File not found at "_variables/Nr.html" for entry with row id "4638" of "DokuWiki.docset"
File not found at "_variables/PRE.html" for entry with row id "4643" of "DokuWiki.docset"
File not found at "_variables/Parser.html" for entry with row id "4644" of "DokuWiki.docset"
File not found at "_variables/QUERY.html" for entry with row id "4645" of "DokuWiki.docset"
File not found at "_variables/R.html" for entry with row id "4646" of "DokuWiki.docset"
File not found at "_variables/RANGE.html" for entry with row id "4647" of "DokuWiki.docset"
File not found at "_variables/REV.html" for entry with row id "4648" of "DokuWiki.docset"
File not found at "_variables/Renderer.html" for entry with row id "4651" of "DokuWiki.docset"
File not found at "_variables/S.html" for entry with row id "4652" of "DokuWiki.docset"
File not found at "_variables/SRC.html" for entry with row id "4654" of "DokuWiki.docset"
File not found at "_variables/SUF.html" for entry with row id "4656" of "DokuWiki.docset"
File not found at "_variables/SUM.html" for entry with row id "4657" of "DokuWiki.docset"
File not found at "_variables/TEXT.html" for entry with row id "4658" of "DokuWiki.docset"
File not found at "_variables/TOC.html" for entry with row id "4659" of "DokuWiki.docset"
File not found at "_variables/USERINFO.html" for entry with row id "4661" of "DokuWiki.docset"
File not found at "_variables/VERSION.html" for entry with row id "4668" of "DokuWiki.docset"
File not found at "_variables/WIDTH.html" for entry with row id "4669" of "DokuWiki.docset"
File not found at "_variables/baseDir.html" for entry with row id "4935" of "DokuWiki.docset"
File not found at "_variables/className.html" for entry with row id "5106" of "DokuWiki.docset"
File not found at "_variables/eventData.html" for entry with row id "5524" of "DokuWiki.docset"
File not found at "_variables/fileInfo.html" for entry with row id "5599" of "DokuWiki.docset"
File not found at "_variables/fileName.html" for entry with row id "5600" of "DokuWiki.docset"
File not found at "_variables/httpClient.html" for entry with row id "5810" of "DokuWiki.docset"
File not found at "_variables/linkType.html" for entry with row id "6145" of "DokuWiki.docset"
File not found at "_variables/maxCols.html" for entry with row id "6243" of "DokuWiki.docset"
File not found at "_variables/methodName.html" for entry with row id "6300" of "DokuWiki.docset"
File not found at "_variables/newValue.html" for entry with row id "6380" of "DokuWiki.docset"
File not found at "_variables/oldValue.html" for entry with row id "6511" of "DokuWiki.docset"
File not found at "_variables/subMatches.html" for entry with row id "7246" of "DokuWiki.docset"
File not found at "_variables/useInput.html" for entry with row id "7478" of "DokuWiki.docset"
File not found at "_variables/userInfo.html" for entry with row id "7491" of "DokuWiki.docset"
File not found at "_variables/A.html" for entry with row id "7670" of "DokuWiki.docset"
File not found at "_variables/ARG.html" for entry with row id "7671" of "DokuWiki.docset"
File not found at "_variables/Abort.html" for entry with row id "7673" of "DokuWiki.docset"
File not found at "_variables/Break.html" for entry with row id "7684" of "DokuWiki.docset"
File not found at "_variables/C.html" for entry with row id "7685" of "DokuWiki.docset"
File not found at "_variables/CONTEXT.html" for entry with row id "7686" of "DokuWiki.docset"
File not found at "_variables/Case.html" for entry with row id "7695" of "DokuWiki.docset"
File not found at "_variables/Cmd.html" for entry with row id "7701" of "DokuWiki.docset"
File not found at "_variables/DATA.html" for entry with row id "7705" of "DokuWiki.docset"
File not found at "_variables/DEFAULT.html" for entry with row id "7707" of "DokuWiki.docset"
File not found at "_variables/DIRECTORY.html" for entry with row id "7710" of "DokuWiki.docset"
File not found at "_variables/Default.html" for entry with row id "7717" of "DokuWiki.docset"
File not found at "_variables/Do.html" for entry with row id "7719" of "DokuWiki.docset"
File not found at "_variables/EDIT.html" for entry with row id "7722" of "DokuWiki.docset"
File not found at "_variables/ELEMENT.html" for entry with row id "7726" of "DokuWiki.docset"
File not found at "_variables/EXTRACT.html" for entry with row id "7730" of "DokuWiki.docset"
File not found at "_variables/Errors.html" for entry with row id "7739" of "DokuWiki.docset"
File not found at "_variables/FileExists.html" for entry with row id "7746" of "DokuWiki.docset"
File not found at "_variables/Handler.html" for entry with row id "7773" of "DokuWiki.docset"
File not found at "_variables/INCLUDE.html" for entry with row id "7776" of "DokuWiki.docset"
File not found at "_variables/INTEGER.html" for entry with row id "7811" of "DokuWiki.docset"
File not found at "_variables/LENGTH.html" for entry with row id "7826" of "DokuWiki.docset"
File not found at "_variables/LICENSE.html" for entry with row id "7829" of "DokuWiki.docset"
File not found at "_variables/LOADER.html" for entry with row id "7830" of "DokuWiki.docset"
File not found at "_variables/LOCATE.html" for entry with row id "7832" of "DokuWiki.docset"
File not found at "_variables/Lexer.html" for entry with row id "7834" of "DokuWiki.docset"
File not found at "_variables/Locate.html" for entry with row id "7838" of "DokuWiki.docset"
File not found at "_variables/Loop.html" for entry with row id "7839" of "DokuWiki.docset"
File not found at "_variables/MAP.html" for entry with row id "7842" of "DokuWiki.docset"
File not found at "_variables/MESSAGE.html" for entry with row id "7844" of "DokuWiki.docset"
File not found at "_variables/MODE.html" for entry with row id "7846" of "DokuWiki.docset"
File not found at "_variables/MTIME.html" for entry with row id "7847" of "DokuWiki.docset"
File not found at "_variables/Mode.html" for entry with row id "7849" of "DokuWiki.docset"
File not found at "_variables/Next.html" for entry with row id "7855" of "DokuWiki.docset"
File not found at "_variables/P.html" for entry with row id "7859" of "DokuWiki.docset"
File not found at "_variables/PID.html" for entry with row id "7862" of "DokuWiki.docset"
File not found at "_variables/SEARCH.html" for entry with row id "7873" of "DokuWiki.docset"
File not found at "_variables/SET.html" for entry with row id "7880" of "DokuWiki.docset"
File not found at "_variables/STATUS.html" for entry with row id "7899" of "DokuWiki.docset"
File not found at "_variables/STRING.html" for entry with row id "7902" of "DokuWiki.docset"
File not found at "_variables/Select.html" for entry with row id "7912" of "DokuWiki.docset"
File not found at "_variables/Silent.html" for entry with row id "7913" of "DokuWiki.docset"
File not found at "_variables/Str.html" for entry with row id "7914" of "DokuWiki.docset"
File not found at "_variables/TAB.html" for entry with row id "7928" of "DokuWiki.docset"
File not found at "_variables/TIME.html" for entry with row id "7929" of "DokuWiki.docset"
File not found at "_variables/TIMEOUT.html" for entry with row id "7930" of "DokuWiki.docset"
File not found at "_variables/TYPE.html" for entry with row id "7934" of "DokuWiki.docset"
File not found at "_variables/USER.html" for entry with row id "7938" of "DokuWiki.docset"
File not found at "_variables/canDo.html" for entry with row id "8057" of "DokuWiki.docset"
File not found at "_variables/computerName.html" for entry with row id "8085" of "DokuWiki.docset"
File not found at "_variables/dirName.html" for entry with row id "8142" of "DokuWiki.docset"
File not found at "_variables/mediaType.html" for entry with row id "8318" of "DokuWiki.docset"
File not found at "_variables/oldAuth.html" for entry with row id "8366" of "DokuWiki.docset"
File not found at "_variables/pluginName.html" for entry with row id "8407" of "DokuWiki.docset"
File not found at "_variables/timeStamp.html" for entry with row id "8553" of "DokuWiki.docset"
```

This happens when you have entries in the docSet.dsidx which point to paths that don't exist (case-sensitive).

**Comment by Kapeli** [comment]
Is this ok to merge?

**Comment by gamma** [comment]
Yes, please merge it.

**Comment by Kapeli** [comment]
Done. Thank you! :+1:

**Pull request closed without merging**
