### PR TITLE
Update boto3 to 1.24.66

### PR DESCRIPTION
**Pull request by jamesoff**

### CODE REVIEW

**Comment by Kapeli** [comment]
You need to update the `docset.json` as well.

**Comment by jamesoff** [comment]
Whoops! Fixed :)

**Comment by Kapeli** [comment]
> Whoops! Fixed :)

I'm not seeing any changes to `docset.json`

**Comment by jamesoff** [comment]
Having one of those days, apparently. Should be there now, sorry.

**Comment by Kapeli** [comment]
Thank you! ❤️

**Pull request merged**
