### PR TITLE
Add Phoenix Framework docsets

### PR DESCRIPTION
**Pull request by k3rni**
This is a combined docset for several projects that make up the [Phoenix framework](https://phoenixframework.org). See https://gitlab.com/k3rni/pxdoc for details and build instructions.

### CODE REVIEW

**Comment by k3rni** [comment]
Note: I'm a Zeal user, so can't test in Dash.

**Comment by Kapeli** [comment]
Dash already has a Phoenix docset in Preferences > Downloads > Hex Docsets > Phoenix. Sorry!

**Comment by k3rni** [comment]
Fair enough, but that one isn't visible in Zeal, thus my attempt (and ignorance).

**Comment by genericlady** [comment]
Is there any way we can not nest it under Hex Docs? It didn't show up when I used the search feature O_o and google didn't easily yield results on how to add them.

**Pull request closed without merging**
