### PR TITLE
Improve EMF XSD SDK docset

### PR DESCRIPTION
**Pull request by tsdh**
The former version had classes indexed with HTML entities, e.g., there
was a generic class EList&lt;E&gt;.  This has been fixed with this
version of the docset and also in the corresponding generation script.

Docset generation script fix:

  https://github.com/tsdh/emf-xsd-sdk/commit/779fa7f04bf753981b6f150a9c817b184a4e6d27

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by tsdh** [comment]
While we are at it: I haven't still be able to figure out how to add all these user-contributed docsets to Zeal (I'm on Linux), nor has a friend of mine who uses Dash on Mac found out.  What is this mysterical CDN where the docsets are pushed to?

**Comment by Kapeli** [comment]
Check out https://github.com/zealdocs/zeal/issues/170#issuecomment-71310603.

**Comment by tsdh** [comment]
Ah, thank you.  And what about Dash itself?  My friend told me that he's been unable to find the EMF XSD SDK docs anywhere in Dash.  I'm not sure if he tried the MacOS X or the iOS version, though.

**Comment by Kapeli** [comment]
Dash for iOS does not support user contributed docsets currently.

EMF XSD SDK is definitely available in Preferences > Downloads > User Contributed in Dash for OS X.

**Comment by tsdh** [comment]
Ok, thanks.

**Pull request merged**
