### PR TITLE
Crystal Docset: v 0.11.0

### PR DESCRIPTION
**Pull request by Fusion**
Crystal Language.

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:

```
Found entry with new line in its name at row id "4271" at "crystal.docset". Complete entry name is: "KeyBindingHandler 
  if (handlers 
    res 
    LibReadline::Int.new(res)
  else
    LibReadline::Int.new(1)
  end
end"
Found entry with new line in its name at row id "5949" at "crystal.docset". Complete entry name is: "ARGV 
  String.new(c_str)
end"
```

Also please remove the Sample_Docset.tgz stuff.

**Comment by Fusion** [comment]
OK, hopefully it's better now. I had to add an ugly bit of bash/sqlite3 code to my script.

**Comment by Kapeli** [comment]
One more issue: the docset's index page (`api/index.html`) doesn't have any CSS styling while the rest of the docset does.

**Comment by Fusion** [comment]
Ack! OK, fixed. Please let me know what else I messed up. Sorry for having you do my QA :/

**Comment by Kapeli** [comment]
Thank you! :+1:

**Pull request closed without merging**
