### PR TITLE
Update Laravel Zero

### PR DESCRIPTION
**Pull request by godbout**
Sorry, there is a mistake in the documentation itself. I've contacted the author but didn't have any answer yet. Still, because of that mistake, the version number I got from the executable is wrong. This is the updated version.

I'm not sure if this would have any consequence, so I didn't remove the 2.2.0 version. But if it's fine, we can delete it.

Thank you!

### CODE REVIEW

**Comment by godbout** [comment]
Also, added much better Guides and Sections.

**Comment by godbout** [comment]
There's an issue with my archiving script, sorry about that. Will update with a valid version. Still learning the process :))

**Comment by godbout** [comment]
I did not touch the 2.2.0 archive, not sure why it shows as changed in the commit. Can be removed probably anyway, as asked above.

**Comment by Kapeli** [comment]
Thank you! 👍 

Regarding 2.2.0 archive: once I merge something I rewrite the git history and remove all archives (to keep the repo size small), so the 2.2.0 archive was removed and probably came back from your repo, that's why it's showing as changed.

**Comment by godbout** [comment]
@Kapeli oops, my bad. Would it be ok if I remove that `2.2.0` version completely, or that might break something on the user's side?

**Comment by Kapeli** [comment]
Nope, it's ok to remove stuff.

**Pull request merged**
