### PR TITLE
update tldr pages to version 0.0.2.33.

### PR DESCRIPTION
**Pull request by Moddus**
update tldr pages to version 0.0.2.33.

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by gingerbeardman** [comment]
Any chance this can be updated again? Pretty please?

**Comment by cvn** [comment]
@gingerbeardman My update for the TLDR pages docset was accepted today. See PR #1764. It should be updated in Dash soon.

**Comment by gingerbeardman** [comment]
Nice work! @cvn

**Pull request merged**
