### PR TITLE
FEATURE: add divio cloud docs

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by Kapeli** [comment]
Failed validation:

```
Checking divio/divio.tgz...
File not found at "py-modindex.html" for entry with row id "247" of "divio.docset"
File not found at "py-modindex.html" for entry with row id "261" of "divio.docset"
```

**Comment by crydotsnake** [comment]
How can i fix this @Kapeli

**Comment by Kapeli** [comment]
You need to remove the entries from docSet.dsidx that point to files that do not exist.

**Comment by crydotsnake** [comment]
How do you edit those files? with vscode?

**Comment by Kapeli** [comment]
How did you generate the file? Usually you need to modify your docset generation script to not include entries that point to files that don't exist.

**Comment by Kapeli** [comment]
Please open an issue on doc2dash's GitHub repo regarding this.

**Review by dpuga1 — APPROVED** [review]

**Pull request closed without merging**
