### PR TITLE
update for llvm 3.7.0

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by Kapeli** [comment]
@iamaziz Is this ok to merge?

**Comment by iamaziz** [comment]
@Kapeli yep I believe it is. Please add @Chilledheart to readme and docset.json for this update.

**Comment by Kapeli** [comment]
Thank you! :+1: 

@Chilledheart If you want you can add yourself to the README and/or docset.json and open a pull request.

**Comment by Chilledheart** [comment]
@Kapeli great

**Pull request merged**
