### PR TITLE
Add psycopg==3.1.15

### PR DESCRIPTION
**Pull request by Florents-Tselai**

### CODE REVIEW

**Comment by Florents-Tselai** [comment]
Hmm, not sure why this is failing.

**Comment by Kapeli** [comment]
The docset archives should contain just the docset and nothing else. Currently the archives contain a folder structure and the docset is located at `/versions/3.1.5/psycopg.docset`.

**Comment by Kapeli** [comment]
Please resubmit a pull request when you're ready.

**Comment by Florents-Tselai** [comment]
The tests here pass though, no ?
Afaicu this is good.

**Comment by Kapeli** [comment]
The tests pass because you removed the docset entirely and no tests are run at all.

**Pull request closed without merging**
