### PR TITLE
Snap.svg

### PR DESCRIPTION
**Pull request by yanick**
for http://snapsvg.io

### CODE REVIEW

**Comment by Kapeli** [comment]
`icon.png` needs to be `16x16` and `icon@2x.png` needs to be `32x32`.

**Comment by yanick** [comment]
icons resized.

**Comment by Kapeli** [comment]
There seems to be a scrolling issue. Add this CSS to `assets/css/main.css` to fix it: `#site {transform:none !important}`

**Comment by yanick** [comment]
CSS tweaked!

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by yanick** [comment]
No, no, thank _you_. :-)

**Pull request merged**
