### PR TITLE
new update

### PR DESCRIPTION
**Pull request by esoftplay**
fix layout

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! 👍

**Comment by esoftplay** [comment]
you're already merge my pull request yesterday, but the docset still not updated from my end. any suggestion?

**Comment by Kapeli** [comment]
You didn't change the `version` in `docset.json`. An update is not triggered if the version is the same. To get the latest docset in Dash currently you need to uninstall and reinstall.

**Comment by esoftplay** [comment]
my bad, thank you

**Pull request merged**
