### PR TITLE
New Reactive Native Docset

### PR DESCRIPTION
**Pull request by epitaphmike**
This React Native Docset is a little different from the React Docset. It has a complete Table of Contents.

### CODE REVIEW

**Comment by epitaphmike** [comment]
Requesting new Supported Entry Types of "Polyfills" and "APIs".

**Comment by Kapeli** [comment]
Needs some changes:

1. Wherever you use `ReactNative` now, change it to `React_Native` (e.g. your project folder).
2. The docset name (in Info.plist) should NOT include the docset version

Great job!

**Comment by Kapeli** [comment]
Entry types: can you give me examples (links) of what you would add as "Polyfill" and "API"?

**Comment by epitaphmike** [comment]
The React Native docs are broken down into Guides, Components, APIs and Polyfills.
http://facebook.github.io/react-native/docs/getting-started.html

I was just trying to stick with their breakdown. If you have another suggestion for Dash, I am open to it.

Thanks.

**Comment by Kapeli** [comment]
All of the other javascript-related docsets use Class as types for those. Personally I'd use Class for everything under Components, APIs and Polyfills. If you disagree and you want me to add those types I can add them in the next update. Let me know.

**Comment by epitaphmike** [comment]
I can stick with what is consistent for Dash. Thanks for the offer though.

**Pull request closed without merging**
