### PR TITLE
Add docset Deno@1.20.2+702568c

### PR DESCRIPTION
**Pull request by aiotter**
Fresh new docset for [Deno](https://deno.land) API!
I'm not sure the versioning fits on Dash. I believe it is best describing the docset version, but please let me know if the build identifier works bad.

And I believe I'm eligible to free Dash license for creating [deno-dash-doc](https://github.com/aiotter/deno-dash-doc) and [deno_api_docset](https://github.com/aiotter/deno_api_docset).
I appreciate it if you send it to yuto@aiotter.com!

### CODE REVIEW

**Comment by Kapeli** [comment]
Entry paths don't have anchors, so for example all Classes point to the top of the same page instead of taking you to the relevant place within that page. Is this intentional?

**Comment by aiotter** [comment]
Woops, sorry. I didn't noticed this. I'll fix it soon.

**Comment by aiotter** [comment]
fixed

**Comment by Kapeli** [comment]
Thank you! 👍

**Pull request merged**
