### PR TITLE
Add Keras 0.3.1

### PR DESCRIPTION
**Pull request by iamaziz**
Request #637

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by Atcold** [comment]
I cannot find Keras between the "Find docsets to download".
Am I missing something?

**Comment by Kapeli** [comment]
Are you in the "User Contributed" section?

**Comment by iamaziz** [comment]
Mmmm not sure why! it's already under User Contributed 
image

**Comment by Atcold** [comment]
I'm on Dash 3.3.1 and this is what I see.

screenshot 2016-10-21 17 49 24

**Comment by Kapeli** [comment]
In the sidebar on the left: scroll up and select User Contributed.

**Comment by Atcold** [comment]
@Kapeli, yes, just saw that. Sorry for polluting the post.

**Pull request merged**
