### PR TITLE
Initial ThinkJS.docset

### PR DESCRIPTION
**Pull request by lizheming**
sorry to bother you, after pr I found something wrong, so I close old one and create new again.

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by lizheming** [comment]
@Kapeli Thank you for your working! And may I ask you how to deal with multi language in docset? Because ThinkJS has English and Chinese Simplified two language version.

**Comment by Kapeli** [comment]
Currently only English docsets are allowed. However, you can make docsets it other languages and distributed them yourself using docset feeds.

**Comment by lizheming** [comment]
OK! I knew it! Thank you very much!

**Pull request closed without merging**
