### PR TITLE
Add Phaser 3 docset

### PR DESCRIPTION
**Pull request by okletzmayr**
I know that Phaser 2 is already in User-Contributions, but since their 3.50.1 update never made it to a PR here, I created my own version - hope that's okay with you. This docset is built with my [improved dashing config](https://github.com/photonstorm/phaser3-docs/pull/129) I suggested in the phaser3-docs repo. Please let me know if the PR needs tweaks.

### CODE REVIEW

**Comment by Kapeli** [comment]
Any reason not to add this as an update to the existing Phaser docset?

The retina icon needs to be named `icon@2x.png`.

**Comment by Kapeli** [comment]
Any reason not to add this as an update to the existing Phaser docset?

**Comment by okletzmayr** [comment]
Sorry for the late response - forgot to leave a comment last time.
No, not really. Phaser 2 is still maintained as a separate Community Edition, but I'd be happy to merge this one into the existing docset as a version.

**Comment by Kapeli** [comment]
Yes, please merge.

**Comment by Kapeli** [comment]
Closing due to inactivity. Please open a new pull request when ready.

**Pull request closed without merging**
